"""Descriptive frozen-policy analysis, no collection or threshold fitting."""
import json,os,random
from fractions import Fraction
from collect_smollm_v47 import ROOT,read,write
os.environ.setdefault('MPLCONFIGDIR',str(ROOT/'.cache/matplotlib'))
SEEDS=[11,23,37,53,71];MODES=['sequential_3nn','batch_3nn','random_projection','random_full','predictor_sweep']
def stats(gs):
 return {'mean_fraction':str(sum(gs)/len(gs)),'mean_percent':float(100*sum(gs)/len(gs)),'wins':sum(g>0 for g in gs),'ties':sum(g==0 for g in gs),'losses':sum(g<0 for g in gs),'paired_percent':[float(100*g) for g in gs]}
def main():
 o=ROOT/'results/v133_native';saved=read(ROOT/'artifacts/study_v133/decisions.json')['rows'];rate=read(ROOT/'artifacts/study_v132/model.json')['benefit_calibration']['selected']['development_rate'];rng=random.Random(133001);matched=set(random.Random(133002).sample(range(5),sum(r['decisions']['benefit'] for r in saved)));rows=[]
 for i,seed in enumerate(SEEDS):
  arms={m:read(o/'arms'/f'{seed}_{m}.json') for m in MODES+['llm']};prefix=read(o/'prefixes'/f'{seed}.json');decision=next(r for r in saved if r['seed']==seed)
  r={'seed':seed,'prefix_best':min(y[0] for y in prefix['labels']),'reference':prefix['labels'][0][0],'default_anchor':prefix['labels'][1][0],**{m:arms[m]['best'] for m in arms},'model_status':arms['llm']['model_status'],'fallback':arms['llm']['fallback'],'decision_seconds':decision['decision_seconds']}
  r['gain_fraction']=str(Fraction(r['sequential_3nn']-r['llm'],r['sequential_3nn']));r['decisions']={'never':False,'always':True,**decision['decisions'],'random_development_rate':rng.random()<rate,'random_matched_realized_rate':i in matched,'hindsight_oracle_diagnostic':r['llm']<r['sequential_3nn']};rows.append(r)
 summary={m:stats([Fraction(r[m]-r['llm'],r[m]) for r in rows]) for m in MODES+['reference','default_anchor','prefix_best']};policies={}
 for policy in rows[0]['decisions']:
  gs=[Fraction(r['gain_fraction']) if r['decisions'][policy] else Fraction(0) for r in rows];policies[policy]={'gain':stats(gs),'modeled_calls':sum(r['decisions'][policy] for r in rows),'missed_benefit_over_1pct':sum(not r['decisions'][policy] and Fraction(r['gain_fraction'])>Fraction(1,100) for r in rows),'harmful_escalation_over_1pct':sum(r['decisions'][policy] and Fraction(r['gain_fraction'])<Fraction(-1,100) for r in rows)}
 model=read(ROOT/'results/v133_proposals/ledger.json');raw=[json.loads(l) for l in (ROOT/'results/v133_proposals/responses.jsonl').read_text().splitlines()];usage={'generated_observed':sum(r['response'].get('tokens_predicted',0) for r in raw),'prefill_observed':sum(r['response'].get('tokens_evaluated',0) for r in raw),'attempts_missing_usage':model['generation_requests']-sum(type(r['response'].get('tokens_predicted')) is int and type(r['response'].get('tokens_evaluated')) is int for r in raw)};ledgers=[read(o/p/'ledger.json') for p in ['classical','continuations']]
 result={'groups':1,'cases':5,'rows':rows,'summary':summary,'policies':policies,'llm_improved_prefix':sum(r['llm']<r['prefix_best'] for r in rows),'classical_improved_prefix':sum(r['sequential_3nn']<r['prefix_best'] for r in rows),'model_ledger':model,'usage':usage,'native_ledgers':ledgers,'scope':'Single new native libjpeg family; frozen historical controller; descriptive, not a Q2 readiness or learned selective benefit claim'};write(o/'comparison.json',result)
 lines=['# V133 lossless JPEG: strong cheap controls and frozen-router transfer','','Three real photographs, one software family, five seeds. Every arm shares B10 and has B20. Correctness requires identical complete RGB pixels. Public photo familiarity, one family, a 70-vector domain and same-library decoder limit generalization.','', '| Comparator | Mean model gain | Wins/ties/losses |','|---|---:|---:|']
 for m,s in summary.items():lines.append(f"|{m}|{s['mean_percent']:+.4f}%|{s['wins']}/{s['ties']}/{s['losses']}|")
 lines += ['', f"Incremental attribution: the model improved {result['llm_improved_prefix']}/5 prefixes; sequential search improved {result['classical_improved_prefix']}/5. A gain against the left-predictor anchor is not automatically a gain caused by escalation. The saved B10 outcomes identify how much was already achieved before the call."]
 lines+=['','The predictor-sweep arm uses documented domain knowledge and charges every acquisition. The predictor-7 reference is not advertised as an expert optimum; the left-predictor anchor is not the ordinary lossy JPEG default. Primary comparison remains sequential 3NN, with predictor sweep a mandatory strong control.','', '| Seed | Prefix bytes | Sequential bytes | Predictor sweep bytes | Model bytes | Paired model gain |','|---:|---:|---:|---:|---:|---:|']
 for r in rows:lines.append(f"|{r['seed']}|{r['prefix_best']}|{r['sequential_3nn']}|{r['predictor_sweep']}|{r['llm']}|{float(Fraction(r['gain_fraction'])*100):+.4f}%|")
 lines+=['','| Policy | Modeled calls | Mean gain vs never | Missed >1% | Harmful >1% |','|---|---:|---:|---:|---:|']
 for p,r in policies.items():lines.append(f"|{p}|{r['modeled_calls']}/5|{r['gain']['mean_percent']:+.4f}%|{r['missed_benefit_over_1pct']}|{r['harmful_escalation_over_1pct']}|")
 lines+=['','Benefit/uncertainty parameters are unchanged from V132 historical training (40 pairs/eight groups); each decision was saved before its classical continuation and before all new model calls. Random development rate is fixed from that calibration. Matched-realized-rate random is a batch diagnostic; hindsight is non-deployable. These now-exposed outcomes may not tune the frozen controller. Zero-rate policies matching never do not demonstrate selective routing advantage.',f"\nActual collection: {sum(l['configuration_attempts'] for l in ledgers)} native configurations, {sum(l['encodes'] for l in ledgers)} encodes and {sum(l['decodes'] for l in ledgers)} decodes; native wall time {sum(l['seconds'] for l in ledgers):.3f} s. All alternatives and three reference repeats are charged. Thirty logical B20 arms share fifty physical prefix trials. Model calls {model['generation_requests']}, retries {model['retries']}, valid {sum(r['model_status']=='valid' for r in rows)}/5, fallbacks {sum(r['fallback'] for r in rows)}; tokens generated/prefill {usage['generated_observed']}/{usage['prefill_observed']}, missing usage {usage['attempts_missing_usage']}. Allocated output tokens {model['allocated_output_tokens']}. Model lifecycle {model['stage_seconds']:.3f} s, startup {model.get('startup_seconds',float('nan')):.3f} s, peak sampled RSS {model['peak_server_rss_bytes']} bytes, server exit {model['server_exit_code']}.",f"\nFeature/prediction time total {sum(r['decision_seconds'] for r in rows):.6f} s; historical original fit time remains unknown. A deployment uses one B20 arm and a model call only if selected, plus decision overhead and explicit model-loading assumptions. This counterfactual cannot erase actual research collection cost. No cloud-dollar/energy savings inferred.",'','Images are full-resolution scikit-image v0.20.0 astronaut/coffee/rocket photographs with owner-verified hashes and documented public-domain/CC0 attribution. Rocket starts as JPEG; its decoded pixels are the fixed input. This is native software-configuration research, not a new codec, a test of broad medical-image suitability, or exact SNAP2 replication. No significance from repeated seeds; no journal-acceptance guarantee.','', 'Reproduce: `.venv/bin/python scripts/analyze_jpeg_v133.py`; verify: `.venv/bin/python scripts/verify_jpeg_v133.py`. Protocol/source audit and raw logs are preserved.']
 (ROOT/'reports/jpeg_v133.md').write_text('\n'.join(lines)+'\n')
 import matplotlib
 matplotlib.use('Agg');import matplotlib.pyplot as plt
 fig,axes=plt.subplots(1,3,figsize=(14,3.8))
 for m in ['sequential_3nn','predictor_sweep']:
  axes[0].plot(SEEDS,summary[m]['paired_percent'],'o-',label=m.replace('_',' '))
 axes[0].axhline(0,color='black',lw=.8);axes[0].set_xticks(SEEDS);axes[0].set_xlabel('Seed (one libjpeg group)');axes[0].set_ylabel('Model gain vs comparator (%)');axes[0].legend(fontsize=8)
 modes=['never','always','benefit','uncertainty'];axes[1].bar(modes,[policies[m]['gain']['mean_percent'] for m in modes]);axes[1].axhline(0,color='black',lw=.8);axes[1].set_ylabel('Policy gain vs never (%)')
 for i,m in enumerate(modes):axes[1].text(i,policies[m]['gain']['mean_percent'],f"{policies[m]['modeled_calls']}/5 calls",ha='center',va='bottom',fontsize=8)
 labels=['left-predictor\nanchor','B10 prefix','sequential\ncontinuation'];vals=[summary[m]['mean_percent'] for m in ['default_anchor','prefix_best','sequential_3nn']];axes[2].bar(labels,vals);axes[2].axhline(0,color='black',lw=.8);axes[2].set_ylabel('Model result gain vs comparator (%)');axes[2].set_ylim(-.6,max(vals)*1.2)
 for i,v in enumerate(vals):axes[2].text(i,v,f'{v:+.4f}%',ha='center',va='bottom',fontsize=8)
 fig.suptitle('V133: exact-pixel native comparison and frozen decisions');fig.tight_layout();fig.savefig(o/'comparison.png',dpi=180,metadata={'Software':'llm-escalation-study V133'});plt.close(fig)
 print(json.dumps({'summary':summary,'policies':policies,'usage':usage},indent=2))
if __name__=='__main__':main()
