"""Evaluate already-frozen decisions; never refit after new paired outcomes."""
import json,os
from fractions import Fraction
from collect_smollm_v47 import ROOT,read,write,sha
os.environ.setdefault('MPLCONFIGDIR',str(ROOT/'.cache/matplotlib'))
def main():
 for n,h in read(ROOT/'reports/protocol_v132.freeze.json')['sha256'].items():assert sha(ROOT/n)==h,n
 art=ROOT/'artifacts/study_v132';out=ROOT/'results/v132_router';out.mkdir(exist_ok=True);decisions=read(art/'decisions.json');paired=read(ROOT/'results/v131_native/comparison.json');rows=[]
 for r in decisions['rows']:
  p=next(p for p in paired['rows'] if p['task']==r['group'] and p['seed']==r['seed'])
  if r['group']=='fftw':c=p['fresh_medians_ns']['sequential_3nn'];l=p['fresh_medians_ns']['llm'];same=p['same_selected_configuration']
  else:c=p['sequential_3nn'];l=p['llm'];same=read(ROOT/f"results/v131_native/arms/wavpack_{r['seed']}_sequential_3nn.json")['incumbent']==read(ROOT/f"results/v131_native/arms/wavpack_{r['seed']}_llm.json")['incumbent']
  gain=Fraction(c-l,c);rows.append({**r,'classical_target':c,'llm_target':l,'paired_gain_fraction':str(gain),'paired_gain_percent':float(gain*100),'same_selected_configuration':same,'decisions':{**r['decisions'],'hindsight_oracle_diagnostic':gain>0}})
 policies={};margin=Fraction(1,100)
 for policy in rows[0]['decisions']:
  bygroup={}
  for group in ['wavpack','fftw']:
   subset=[r for r in rows if r['group']==group];gain=sum(Fraction(r['paired_gain_fraction']) if r['decisions'][policy] else 0 for r in subset)/len(subset)
   bygroup[group]={'gain_fraction':str(gain),'gain_percent':float(gain*100),'escalations':sum(r['decisions'][policy] for r in subset),'missed_gt_1pct':sum(Fraction(r['paired_gain_fraction'])>margin and not r['decisions'][policy] for r in subset),'harmful_gt_1pct':sum(Fraction(r['paired_gain_fraction'])< -margin and r['decisions'][policy] for r in subset)}
  policies[policy]={'by_group':bygroup,'equal_group_gain_percent':sum(g['gain_percent'] for g in bygroup.values())/2,'escalations':sum(g['escalations'] for g in bygroup.values()),'modeled_requests':None if policy=='hindsight_oracle_diagnostic' else sum(g['escalations'] for g in bygroup.values()),'missed_gt_1pct':sum(g['missed_gt_1pct'] for g in bygroup.values()),'harmful_gt_1pct':sum(g['harmful_gt_1pct'] for g in bygroup.values())}
 equivalence={'label':'Post-hoc action-equivalence diagnostic; original raw primary comparisons retained','same_configuration_cases':sum(r['same_selected_configuration'] for r in rows),'raw_gt_1pct_benefits':sum(Fraction(r['paired_gain_fraction'])>margin for r in rows),'different_configuration_gt_1pct_benefits':sum(Fraction(r['paired_gain_fraction'])>margin and not r['same_selected_configuration'] for r in rows),'different_configuration_gt_1pct_harms':sum(Fraction(r['paired_gain_fraction'])< -margin and not r['same_selected_configuration'] for r in rows)}
 write(out/'comparison.json',{'training_groups':8,'test_groups':2,'test_cases':10,'rows':rows,'policies':policies,'practical_margin':.01,'action_equivalence_diagnostic':equivalence,'model_and_thresholds_frozen':sha(ROOT/'reports/protocol_v132.freeze.json'),'new_model_requests':0,'new_native_trials':0,'original_controller_fit_wall_seconds':None,'scope':'Outcome-blind decision transfer; tiny two-family evaluation, no evidence of selective routing when policies collapse'})
 lines=['# V132: frozen historical controller, two new families','','All ten decisions were frozen before V131model-continuation or fresh timing-validation outcomes were acquired. Eight historical training groups/40cases; two new groups/10cases. Features use only B10observations and feature-domain metadata. No new model or native trials beyond charged V131collection.','', '| Policy | Calls /10 | WavPack gain | FFTW fresh gain | Missed >1% | Harmful >1% |','|---|---:|---:|---:|---:|---:|']
 for p,v in policies.items():lines.append(f"|{p}|{v['escalations']}|{v['by_group']['wavpack']['gain_percent']:+.4f}%|{v['by_group']['fftw']['gain_percent']:+.4f}%|{v['missed_gt_1pct']}|{v['harmful_gt_1pct']}|")
 lines+=['','The hindsight row is non-deployable: it uses observed outcomes to pick the branch and cannot be assigned an ordinary model-call cost. Matched-realized random uses only the saved pre-decision escalation count but is a batch diagnostic. Practical1%benefit/harm counts use raw paired outcomes; FFTWsame-configuration differences are timing variability, not evidence of distinct configuration benefit.',f"\nBenefit controller selected {policies['benefit']['escalations']}/10 escalations. Uncertainty selected {policies['uncertainty']['escalations']}/10. When both collapse to never, neither establishes learned selective advantage or H1/H2; their identical scores/call counts must not be presented as superiority over a classical baseline. Actual V131research still used10model calls to observe both branches; counterfactual deployment counts do not erase those costs.",'','Development-only calibration used leave-one-group-out ridge predictions (training-only scaling, group weights) for benefit and fixed acquired-label bootstrap-best dispersion for uncertainty. Thresholds maximize development paired gain, breaking ties toward fewer calls. The resulting zero development rate is retained without forcing a favorable nonzero rate. Heterogeneous historical treatment/output contracts, selection metrics and task domains limit transfer interpretation. SACstructural failures were excluded from model fitting only and remain in historical reliability/cost denominators.','', 'Two test families cannot establish population generalization, confidence bounds, superiority, novelty or Q2readiness. No re-fitting, test threshold selection, rerouting after outcomes or deletion of failures occurred. Every family retains all five seeds.','', 'Reproduce `.venv/bin/python scripts/analyze_router_v132.py`; decisions/model/development folds: `artifacts/study_v132/`; paired source: `results/v131_native/`; protocol/freeze: `reports/protocol_v132.md` and `.freeze.json`.']
 lines += ['',f"Post-hoc action-equivalence diagnostic: {equivalence['raw_gt_1pct_benefits']} raw >1%benefit cases, but {equivalence['different_configuration_gt_1pct_benefits']} involved different selected configurations. {equivalence['different_configuration_gt_1pct_harms']} >1%harm cases involved different settings. Thus the raw missed-benefit counter includes same-configuration timing variability. Do not advertise it as a demonstrated missed better configuration, or reinterpret this diagnostic as a population guarantee. The original raw primary and oracle rows are preserved.",'','Original controller fitting/decision wall time was not recorded and is unknown, not zero. Saved coefficients/predictions can be replayed, but replay timing would be a separate measurement.']
 (ROOT/'reports/router_v132.md').write_text('\n'.join(lines)+'\n')
 print(json.dumps({'policies':policies},indent=2))
if __name__=='__main__':main()
