"""Format-only comparison, preserving original V124 errors and denominators."""
import json,math
from collect_smollm_v47 import ROOT,read,write,sha
from format_probe_v125 import messages
from surrogate_v124 import parse,payload,messages as original_messages
OUT=ROOT/'results/v125_analysis'
def main():
 for name in ['reports/protocol_v125.freeze.json','artifacts/study_v125/inputs.freeze.json']:
  for n,h in read(ROOT/name)['sha256'].items():assert sha(ROOT/n)==h,n
 OUT.mkdir(exist_ok=False);jobs=read(ROOT/'artifacts/study_v125/jobs.json');ledger=read(ROOT/'results/v125_format/ledger.json');starts=[json.loads(x) for x in (ROOT/'results/v125_format/generation_starts.jsonl').read_text().splitlines()];raw=[json.loads(x) for x in (ROOT/'results/v125_format/responses.jsonl').read_text().splitlines()];old={r['key']:r for r in [json.loads(x) for x in (ROOT/'results/v124_surrogate/responses.jsonl').read_text().splitlines()]};rm={r['key']:r for r in raw};sm={s['identity']:s for s in starts};rows=[]
 assert len(starts)==len(sm)==ledger['generation_requests']<=18 and len(raw)==len(rm)<=len(starts);assert ledger['allocated_output_tokens']==32*len(starts)<=576 and ledger['retries']==ledger['external_spend_usd']==0 and ledger['peak_server_rss_bytes']<=8589934592 and ledger['stage_seconds']<=500
 assert [s['identity'] for s in starts]==[j['key'] for j in jobs[:len(starts)]]
 for j in jobs:
  p=read(ROOT/j['prefix']);spec=next(s for s in read(ROOT/'data/manifest_v41.json')['datasets'] if s['id']==j['dataset']);expected=messages(p,j['candidate_id'],spec['meaning'],j['condition']);assert expected==read(ROOT/j['messages_path']);pre=read(ROOT/f"results/v125_format/preflight/{j['key']}.json");assert pre['messages']==expected and len(pre['prompt_tokens'])+32<=4096
  original_pre=read(ROOT/f"results/v124_surrogate/preflight/{j['original_request_key']}.json");assert original_pre['messages']==original_messages(p,j['candidate_id'],spec['meaning'])
  r=rm.get(j['key']);previous=old.get(j['original_request_key']);record={**j,'valid':False,'prediction':None,'error':'unreturned','original_valid':False,'original_prediction':None,'original_error':'unreturned'}
  for source,label in [(r,''),(previous,'original_')]:
   if source is not None:
    try:record[label+'prediction']=parse(source['response']);record[label+'valid']=True;record[label+'error']=None
    except ValueError as e:record[label+'error']=str(e)
  if r is not None:
   request=sm[j['key']]['payload'];assert request==payload(pre['rendered']['prompt'],j['sampling_seed']) and r['response']['prompt']==request['prompt']
   for k in ['seed','n_predict','temperature','top_p','top_k','min_p','repeat_penalty']:assert math.isclose(r['response']['generation_settings'][k],request[k],rel_tol=0,abs_tol=1e-6)
  rows.append(record)
 summary={condition:{'intended':9,'valid':sum(r['valid'] for r in rows if r['condition']==condition),'original_valid_same9':sum(r['original_valid'] for r in rows if r['condition']==condition)} for condition in ['marked_json','reference_text']};usage={f:{'observed_sum':sum(r['response'][f] for r in raw if type(r['response'].get(f)) is int),'missing_receipts':18-sum(type(r['response'].get(f)) is int for r in raw)} for f in ['tokens_predicted','tokens_evaluated']}
 result={'scope':'Development format feasibility only, selected after observed V124HIPAcc format failures but before new inference; no quality or held-out claim','conditions':summary,'cases':rows,'cost':ledger,'usage':usage,'new_objective_acquisitions':0,'original_scheduled_request_references':9,'original_responses_sha256':sha(ROOT/'results/v124_surrogate/responses.jsonl'),'feasibility_rule':'At least8of9valid scalar responses for a condition; no inferred optimization benefit','feasible_conditions':[k for k,v in summary.items() if v['valid']>=8]};write(OUT/'comparison.json',result)
 lines=['# V125: demonstrated answer format, development-only diagnostic','','After observing V124HIPAcc placeholder echoes, freeze two serialization changes on the first3candidate IDs and the same3sampling seeds. No hidden objective labels were acquired. marked_json changes only the observed performance strings by surrounding each numeric example with the requested markers; reference_text uses the owner-style demonstrated answer layout with actual feature names and software-task wording. All other model/sampling settings remain fixed. The original nine V124responses are real compatible same-prefix/seed comparators, not regenerated or repaired. This is a narrow, post-failure development diagnostic, not a held-out method comparison.','','| Condition | Valid /9 | Original same9valid |','|---|---:|---:|']
 for k,v in summary.items():lines.append(f"| {k} | {v['valid']} | {v['original_valid_same9']} |")
 lines+=['',f"Frozen feasibility rule≥8/9valid: {', '.join(result['feasible_conditions']) or 'neither condition'}. No optimization-quality criterion was evaluated. Format success cannot establish useful predictions, uncertainty calibration or router benefit. V124's original invalid statuses and primary verdict remain unchanged.",'',f"Actual new cost: {ledger['generation_requests']}local requests, {usage['tokens_predicted']['observed_sum']}observed generated tokens ({usage['tokens_predicted']['missing_receipts']}missing receipts), {ledger['allocated_output_tokens']}allocated output tokens, {ledger['stage_seconds']:.3f}s lifecycle; zero new objective acquisitions. No retries, imputation, paid/cloud calls or downloads. Original9requests retain their V124collection cost. Full new and old prompt/response identities, raw outputs and denominators are saved.",'','Candidate IDs were used only to select the first three in saved order, never passed to the model. The JSON marker condition isolates one serialization change; reference_text changes several serialization/context details and cannot isolate a single cause. Three candidates from one exposed prefix cannot generalize. Any subsequent optimization run must separately freeze its protocol and use the same strong controls; do not claim the format probe rescued optimization.']
 (ROOT/'reports/format_probe_v125.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'conditions':summary,'feasible_conditions':result['feasible_conditions'],'new_requests':ledger['generation_requests'],'new_objective_acquisitions':0},indent=2))
if __name__=='__main__':main()
