"""Reproducible missing-aware analysis of the complete V144–V145 ledger."""
import json,statistics,math
from fractions import Fraction
from pathlib import Path
from collect_smollm_v47 import ROOT,read,write,sha
A=ROOT/'artifacts/study_v144';O=ROOT/'results/v145_spark'
MODES=['sequential_3nn','adaptive_neighbor','fixed_neighbor','random_full','random_proposal']
APPS=['bayes','pagerank','terasort','tpch','wordcount']
MODELS=['smollm3_3b','qwen3_8b']
def gain(a,b):return float((Fraction(str(a))-Fraction(str(b)))/Fraction(str(a)))
def missing(arm):return any(y[0] is None for y in arm['state']['labels'])
def mean(values):return statistics.mean(values) if values else None
def summary(rows):
 usable=[r for r in rows if r['scorable']];groups={a:[r for r in usable if r['app']==a] for a in APPS};means={a:mean([r['gain'] for r in rs]) for a,rs in groups.items()}
 return {'intended':len(rows),'scorable':len(usable),'inconclusive':len(rows)-len(usable),'mean_gain_complete_pairs':mean([r['gain'] for r in usable]),'equal_workload_mean_complete_pairs':mean([x for x in means.values() if x is not None]),'workload_means_complete_pairs':means,'workload_denominators':{a:len(rs) for a,rs in groups.items()},'wins':sum(r['gain']>0 for r in usable),'ties':sum(r['gain']==0 for r in usable),'losses':sum(r['gain']<0 for r in usable),'practical_wins':sum(r['gain']>.01 for r in usable),'practical_harm':sum(r['gain']<-.01 for r in usable),'all_observed_best_mean_sensitivity':mean([r['gain'] for r in rows])}
def main():
 jobs=read(A/'jobs.json');decisions={r['key']:r for r in read(A/'decisions.json')['rows']};cases=[];stats={}
 for model in MODELS:
  for j in jobs:
   arm=read(O/'models'/f"{model}_{j['key']}.json");controls={k:read(O/'classical'/f"{j['key']}_{k}.json") for k in MODES};g={k:{'gain':gain(c['target'],arm['target']),'scorable':not missing(c) and not missing(arm),'control_missing':missing(c),'model_missing':missing(arm)} for k,c in controls.items()};p=read(ROOT/j['prefix']);d=decisions[j['key']];seq=g['sequential_3nn'];policies={}
   for k,v in {'never':False,'always':True,**{k:d[k] for k in ['benefit','uncertainty','random_matched_rate']}}.items():policies[k]={'escalate':v,'gain':seq['gain'] if v else 0.,'scorable':seq['scorable'] or not v,'harmful_call':v and seq['scorable'] and seq['gain']<-.01,'missed_useful_call':not v and seq['scorable'] and seq['gain']>.01,'usefulness_unknown':not seq['scorable']}
   cases.append({'key':j['key'],'model':model,'app':j['app'],'seed':j['seed'],'model_best_observed':arm['target'],'control_best_observed':{k:c['target'] for k,c in controls.items()},'prefix_best':min(y[0] for y in p['labels']),'model_missing':missing(arm),'model_status':arm['status'],'fallback':arm['fallback'],'contrasts':g,'policies':policies})
  rows=[r for r in cases if r['model']==model];bycontrast={mode:summary([{'app':r['app'],**r['contrasts'][mode]} for r in rows]) for mode in MODES};joint=[r for r in rows if all(r['contrasts'][m]['scorable'] for m in ['sequential_3nn','adaptive_neighbor'])];pol={k:{**summary([{'app':r['app'],**r['policies'][k]} for r in rows]),'calls':sum(r['policies'][k]['escalate'] for r in rows),'harmful_calls':sum(r['policies'][k]['harmful_call'] for r in rows),'missed_useful_calls':sum(r['policies'][k]['missed_useful_call'] for r in rows),'usefulness_unknown_cases':sum(r['policies'][k]['usefulness_unknown'] for r in rows)} for k in rows[0]['policies']}
  bases=([ROOT/'results/v144_models'/model] if model=='smollm3_3b' else [])+[ROOT/'results/v145_models'/model];ledgers=[read(b/'ledger.json') for b in bases];responses=[json.loads(s) for b in bases for s in (b/'responses.jsonl').read_text().splitlines()];starts=sum(x['generation_requests'] for x in ledgers);missing_usage=starts-len(responses)+sum(not isinstance(r['response'].get('tokens_predicted'),int) or not isinstance(r['response'].get('tokens_evaluated'),int) for r in responses);diags=[d for p in (O/'models').glob(model+'_*.json') for d in read(p)['projection']]
  stats[model]={'contrasts':bycontrast,'policies':pol,'joint_comparable':len(joint),'joint_inconclusive':25-len(joint),'joint_practical_wins':sum(all(r['contrasts'][m]['gain']>.01 for m in ['sequential_3nn','adaptive_neighbor']) for r in joint),'fallbacks':sum(r['fallback'] for r in rows),'prefix_improvements_observed_only':sum(r['model_best_observed']<r['prefix_best'] for r in rows),'projection':{'count':len(diags),'nonzero':sum(d['distance']>0 for d in diags),'repeated':sum(d['repeated_proposal'] for d in diags),'matches_prefix':sum(d['matches_prefix'] for d in diags)},'cost':{'request_starts':starts,'complete_responses':len(responses),'missing_usage_requests':missing_usage,'observed_generated_tokens_lower_bound':sum(r['response'].get('tokens_predicted',0) for r in responses),'observed_prefill_tokens_lower_bound':sum(r['response'].get('tokens_evaluated',0) for r in responses),'allocated_output_tokens':sum(l['allocated_output_tokens'] for l in ledgers),'lifecycle_seconds':sum(l['stage_seconds'] for l in ledgers),'startup_seconds':sum(l.get('startup_seconds',0) for l in ledgers),'completed_request_wall_seconds':sum(r['wall_seconds'] for r in responses),'peak_server_rss_bytes':max(l['peak_server_rss_bytes'] for l in ledgers),'server_exit_codes':[l['server_exit_code'] for l in ledgers],'retries':sum(l['retries'] for l in ledgers)},'hindsight_complete_pair_mean_gain_diagnostic':mean([max(0,r['contrasts']['sequential_3nn']['gain']) for r in rows if r['contrasts']['sequential_3nn']['scorable']])}
 ev=[json.loads(x) for x in (O/'acquisitions.jsonl').read_text().splitlines()];miss=[e for e in ev if e.get('value') is None];result={'scope':'Single Spark family, five workloads, five seeds; exploratory missing-data amendment','models':stats,'cases':cases,'collection':read(O/'completion.json'),'charged_acquisitions':len(ev),'finite_acquisitions':len(ev)-len(miss),'missing_acquisitions':len(miss),'missing_rows':sorted({(e['key'].removeprefix('smollm3_3b_').removeprefix('qwen3_8b_').split('_')[0],e['source_line']) for e in miss})};write(O/'comparison.json',result)
 lines=['# V144–V145 Spark extension: measured result and missing-data recovery','',result['scope']+'. The original strict validation failed on a missing TPC-H target. All intended cases and collection costs remain; this is not pristine confirmation or evidence of journal acceptance.','',f"Completed 175 B20arms from 25 shared B10 prefixes. {len(ev)} charged recorded acquisitions: {len(ev)-len(miss)} finite durations and {len(miss)} missing outcomes. {sum(s['cost']['request_starts'] for s in stats.values())} genuine local request starts, {sum(s['cost']['complete_responses'] for s in stats.values())} complete responses, {sum(s['cost']['missing_usage_requests'] for s in stats.values())} incomplete requests with unknown usage and {50-sum(s['cost']['request_starts'] for s in stats.values())} unattempted intents. All failed/unattempted intents use explicitly labeled classical fallback. Original Spark jobs were executed by source authors; we only queried recorded tables.",'', '| Model | Sequential gain* | Comparable /25 | Adaptive gain* | Comparable /25 | >1% win over both / comparable |','|---|---:|---:|---:|---:|---:|']
 for m,s in stats.items():
  q=s['contrasts']['sequential_3nn'];a=s['contrasts']['adaptive_neighbor'];lines.append(f"| {m} | {100*q['equal_workload_mean_complete_pairs']:.4f}% | {q['scorable']} | {100*a['equal_workload_mean_complete_pairs']:.4f}% | {a['scorable']} | {s['joint_practical_wins']}/{s['joint_comparable']} |")
 lines+=['','*Positive favors LLM. Means weight workloads equally, using only complete pairs within each workload. All 25 sequential and adaptive comparisons are complete for each model. Only one random-row comparison per model is inconclusive; missingness can bias that control’s complete-pair summary. A pair with any missing acquisition on either arm is inconclusive for true best duration. Best-observed values, missing flags and sensitivity aggregates for **all 25 cases/model** are preserved in comparison.json. No missing value was imputed as a runtime or silently dropped.','', '| Model / workload | Sequential gain (n) | Adaptive gain (n) | Random prototypes gain (n) |','|---|---:|---:|---:|']
 for m,s in stats.items():
  for app in APPS:
   vals=[]
   for k in ['sequential_3nn','adaptive_neighbor','random_proposal']:
    q=s['contrasts'][k];v=q['workload_means_complete_pairs'][app];vals.append(('unknown' if v is None else f'{100*v:.4f}%')+f" ({q['workload_denominators'][app]}/5)")
   lines.append('| '+m+' / '+app+' | '+' | '.join(vals)+' |')
 lines+=['','## All controls and reliability','', '| Model / control | Wins / ties / losses on complete pairs | >1% wins | <−1% harms | Inconclusive /25 | Observed-best mean sensitivity** |','|---|---|---:|---:|---:|---:|']
 for m,s in stats.items():
  for k,q in s['contrasts'].items():lines.append(f"| {m} / {k} | {q['wins']}/{q['ties']}/{q['losses']} | {q['practical_wins']} | {q['practical_harm']} | {q['inconclusive']} | {100*q['all_observed_best_mean_sensitivity']:.4f}% |")
 lines+=['','**Sensitivity uses the best among available finite acquisitions even for incomplete arms. It does not estimate true complete-arm quality. No significance or equivalence claim.','', '## Frozen controller transport','', 'No fitting or threshold changes on Spark. Original V132 model/thresholds and pre-continuation decisions are retained. Qwen-trained controller on SmolLM is an uncalibrated transfer diagnostic. All 25 Spark cases exceed the development range for mean domain cardinality (55.57–58.63 vs 1.71–4.67); other individual feature ranges overlap. This is extrapolation, not evidence of calibrated benefit prediction. The support audit is artifacts/study_v145/router_transport_audit.json. Random decisions exactly match the realized benefit-controller call count.','', '| Model / policy | Calls /25 | Conditional mean gain* | Inconclusive | Harmful calls | Missed useful | Usefulness unknown |','|---|---:|---:|---:|---:|---:|---:|']
 for m,s in stats.items():
  for k,q in s['policies'].items():lines.append(f"| {m} / {k} | {q['calls']} | {100*q['equal_workload_mean_complete_pairs']:.4f}% | {q['inconclusive']} | {q['harmful_calls']} | {q['missed_useful_calls']} | {q['usefulness_unknown_cases']} |")
 for m,s in stats.items():
  lines+=['',f"{m}: hindsight oracle gain on complete sequential/model pairs {100*s['hindsight_complete_pair_mean_gain_diagnostic']:.4f}% (non-deployable diagnostic on the evaluated cases). Best-observed prefix improvements {s['prefix_improvements_observed_only']}/25. Fallbacks {s['fallbacks']}; projection diagnostics{s['projection']}.",'']
 lines+=['## Collection cost versus deployment scenario','',f"Actual collection consumed {result['collection']['total_collection_seconds']:.3f}s from original first prefix through final outcome; capped at 1,800s. 2,000 acquisitions include 250 prefix + 1,250 classical + 500 model/fallback, across all treatments. Copied/imported histories are counted once. The 6 original SmolLM requests include the interrupted one; repaired collection could use only 44 unused starts; actual counts below reflect runtime guards. No generation retry. The failed orchestration gate is preserved and the repaired collector requires classical completion before starting. No new weights/runtime/packages, paid inference, cloud use or new native Spark jobs.",'']
 for m,s in stats.items():
  c=s['cost'];lines.append(f"{m}: {c['request_starts']}starts/{c['complete_responses']}complete; observed generated≥{c['observed_generated_tokens_lower_bound']}, prefill≥{c['observed_prefill_tokens_lower_bound']}tokens; unknown-usage requests{c['missing_usage_requests']}; allocated{c['allocated_output_tokens']}; lifecycle{c['lifecycle_seconds']:.3f}s, startup{c['startup_seconds']:.3f}s, completed-response request wall{c['completed_request_wall_seconds']:.3f}s, peakRSS{c['peak_server_rss_bytes']}bytes, server exits{c['server_exit_codes']}.")
 lines+=['','A deployment policy after B10 uses 10 new outcomes and at most one generation request; model loading needs a separate amortization assumption. All-control/two-model collection is larger than one policy deployment. Timings include different model blocks; no speed causality, source-unit-to-dollar, energy, or native-runtime savings claim.','', '## Limits and next experiment','', 'Only **one independent software family** was added. Workloads/seeds are dependent; missing durations, uncertain source-wide failure denominator, single historical durations, unverified runtime noise/correctness and public-data contamination constrain the claim. 30 feature inputs use transductive scaling and a fixed ten-level numeric proposal grid; random-proposal control tests this representation. This differs from prior nominal experiments. The amendment was frozen after partial classical outcomes and is explicitly exploratory. More seeds/prompt searches here would not supply an independent-family confirmation.','', 'Next priority: admit further independent systems with documented measured targets and an explicit missing/failure rule before collection, then run a single frozen cross-family confirmation. A successful learned escalation controller is not established by repeated never-call behavior. Negative results are retained alongside workload exceptions; journal quartile readiness is not certified.','', 'Evidence: raw results/v144_models and results/v145_models; original failed acquisitions/results/v144_spark; consolidated imported-plus-new ledger/results/v145_spark; protocol_v144.md and protocol_v145.md; feature-only source_audit_v143.md; source hashes and pre-decision inputs/artifacts/study_v144. Replay `.venv/bin/python scripts/verify_spark_v145.py`; regenerate `MPLCONFIGDIR=/tmp/mpl-v145 .venv/bin/python scripts/report_spark_v145.py`.']
 (ROOT/'reports/spark_v145.md').write_text('\n'.join(lines)+'\n')
 import matplotlib;matplotlib.use('Agg')
 import matplotlib.pyplot as plt
 plt.rcParams['svg.hashsalt']='v145';fig,axes=plt.subplots(1,2,figsize=(11,4.5),sharey=True)
 for ax,k in zip(axes,['sequential_3nn','adaptive_neighbor']):
  for i,m in enumerate(MODELS):
   q=stats[m]['contrasts'][k];vals=[100*q['workload_means_complete_pairs'][a] if q['workload_means_complete_pairs'][a] is not None else float('nan') for a in APPS];ax.bar([j+(i-.5)*.34 for j in range(5)],vals,width=.34,label=m)
  ax.axhline(0,color='black',lw=.8);ax.set_xticks(range(5),APPS,rotation=20);ax.set_title('LLM gain vs '+k);ax.set_ylabel('Mean gain on complete pairs (%)');ax.grid(axis='y',alpha=.2)
 axes[0].legend(fontsize=8);fig.suptitle('One Spark family • five workloads × five seeds\nAll shown pairs complete; one random-row control comparison unresolved');fig.tight_layout();fig.savefig(O/'comparison.png',dpi=160);fig.savefig(O/'comparison.svg',metadata={'Date':None});plt.close(fig)
 print(json.dumps({m:{'sequential':s['contrasts']['sequential_3nn'],'adaptive':s['contrasts']['adaptive_neighbor'],'joint_wins':s['joint_practical_wins'],'cost':s['cost']} for m,s in stats.items()},indent=2))
if __name__=='__main__':main()
