"""Offline diagnostic analysis; full-table timing never feeds an optimizer or router."""
import json,statistics
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from headroom_v165 import summarize_cells
ROOT=Path(__file__).resolve().parents[1];A=ROOT/'artifacts/study_v165';O=ROOT/'results/v165_headroom'
def read(p):return json.loads(p.read_text())
def contrast(target,reference):
 gap=(target['median']-reference['median'])/target['median'];stable=all(x['valid'] and x['relative_mad']<=.05 and x['median']>=.01 for x in [target,reference]);return {'headroom':gap,'same_reference_setting':target['row_id']==reference['row_id'],'stable_quality_comparison':stable,'robust_practical_headroom':gap>.1 and target['row_id']!=reference['row_id'] and stable}
def main():
 raw=[read(O/'acquisitions'/f'{i:03d}.json') for i in range(1,769)];selection=summarize_cells(raw[:384]);validation=summarize_cells(raw[384:]);refs=read(O/'selected_reference.json');v={(x['engine'],x['row_id']):x for x in validation};rows=[];summaries=[];reference_checks=[]
 for t in read(A/'targets.json'):
  selected=next(x for x in refs if x['engine']==t['engine']);r=v[t['engine'],selected['row_id']];x=v[t['engine'],t['row_id']];rows.append({**t,'reference_id':r['row_id'],'validation_median':x['median'],'reference_validation_median':r['median'],**contrast(x,r)})
 for e in ['ripgrep','hnswlib']:
  selected=next(x for x in refs if x['engine']==e);r=v[e,selected['row_id']];allv=[x for x in validation if x['engine']==e];best=min((x for x in allv if x['valid']),key=lambda x:(x['median'],x['row_id']));reference_checks.append({'engine':e,'selected_id':r['row_id'],'selection_median':selected['median'],'validation_median':r['median'],'validation_relative_mad':r['relative_mad'],'validation_valid':r['valid'],'validation_rank':1+sum(x['valid'] and x['median']<r['median'] for x in allv),'posthoc_validation_minimum_id':best['row_id'],'posthoc_validation_minimum':best['median'],'validation_candidates_robustly_better_than_reference':sum(contrast(r,x)['robust_practical_headroom'] for x in allv),'unstable_selection_cells':sum(x['relative_mad']>.05 for x in selection if x['engine']==e),'unstable_validation_cells':sum(x['relative_mad']>.05 for x in allv),'quality_failing_selection_cells':sum(not x['valid'] for x in selection if x['engine']==e),'quality_failing_validation_cells':sum(not x['valid'] for x in allv)})
  for checkpoint in [4,7,10]:
   rr=[x for x in rows if x['kind']=='prefix' and x['engine']==e and x['checkpoint']==checkpoint];summaries.append({'engine':e,'checkpoint':checkpoint,'cases':len(rr),'mean_headroom':statistics.mean(x['headroom'] for x in rr),'min_headroom':min(x['headroom'] for x in rr),'max_headroom':max(x['headroom'] for x in rr),'robust_practical_cases':sum(x['robust_practical_headroom'] for x in rr),'same_reference_setting_cases':sum(x['same_reference_setting'] for x in rr),'unstable_or_invalid_comparisons':sum(not x['stable_quality_comparison'] for x in rr)})
 coll={'new_outcomes':len(raw),'native_invocations':sum(x['measurement']['native_invocations'] for x in raw),'quality_penalties':sum(x['status']=='quality_penalty' for x in raw),'objective_seconds':sum(x['measurement']['objective_seconds'] for x in raw),'subprocess_seconds':sum(x['collection_seconds'] for x in raw),'stage_seconds':read(O/'completion.json')['seconds'],'new_model_requests':0}
 result={'scope':'Post-outcome development diagnostic; full-space outcomes are offline research costs outside B20 policy budgets','selection_cells':selection,'validation_cells':validation,'reference_checks':reference_checks,'targets':rows,'prefix_summary':summaries,'collection':coll};(O/'comparison.json').write_text(json.dumps(result,indent=2)+'\n')
 text=['# V165: how much opportunity remains after the cheap prefix?','','This separately charged development diagnostic exhaustively measures both exposed 64-setting application domains. It selects a reference using three repetitions and evaluates every setting on three fresh repetitions. The reference is an empirical finite-domain comparator, not a proven global optimum. No optimizer, router or LLM received these full-space outcomes. Earlier primary results remain unchanged.','','## Prefix opportunity on fresh validation','','Positive headroom means the selected reference is faster than the frozen prefix incumbent. Robust flags require >10%, different settings, correct/quality-feasible validation, relative MAD<=5% and both medians>=10ms. All checkpoints share the original ten-evaluation trajectory; these are not new handoff experiments.','','| Application | Acquired prefix labels | Mean observed headroom | Range | Robust >10% cases / 5 | Same reference setting / 5 | Unstable/invalid comparisons |','|---|---:|---:|---:|---:|---:|---:|']
 for x in summaries:text.append(f"| {x['engine']} | {x['checkpoint']} | {100*x['mean_headroom']:+.3f}% | {100*x['min_headroom']:+.3f}% to {100*x['max_headroom']:+.3f}% | {x['robust_practical_cases']} | {x['same_reference_setting_cases']} | {x['unstable_or_invalid_comparisons']} |")
 text+=['','## Reference selection and noise','','| Application | Selected ID | Selection / validation median seconds | Validation rank / 64 | Validation MAD | Other settings robustly >10% faster |','|---|---:|---:|---:|---:|---:|']
 for x in reference_checks:text.append(f"| {x['engine']} | {x['selected_id']} | {x['selection_median']:.6f} / {x['validation_median']:.6f} | {x['validation_rank']} | {100*x['validation_relative_mad']:.3f}% | {x['validation_candidates_robustly_better_than_reference']} |")
 text+=['','The validation rank/minimum uses all fresh labels only as an explicitly post-hoc diagnostic; it never replaces the reference selected before validation. Selecting the minimum of64 noisy medians may overfit selection noise. Three independent validation repetitions reduce reuse bias but cannot certify global optimality, a risk bound or equivalence. Negative observed headroom is retained. Same-setting comparisons share one validated value and are exactly zero; this does not retroactively remove the separately timed noise in V163/V164.','','All90 V164 frozen arm incumbents are also mapped onto this common validation table in comparison.json, as a diagnostic only. No original primary estimate is overwritten and the768 extra evaluations are not hidden inside a B20 policy budget.','','## Actual execution and reproducibility','',f"New collection: {coll['new_outcomes']} configuration outcomes / {coll['native_invocations']} native workload invocations, zero model calls. Selection384 outcomes and validation384 outcomes cover all128 settings three times each. Every attempt is charged. Quality penalties:{coll['quality_penalties']}. Native subprocess{coll['subprocess_seconds']:.3f}s, objective{coll['objective_seconds']:.3f}s, stage{coll['stage_seconds']:.3f}s/1800s. Historical100prefix outcomes/300invocations and prior inference remain separate existing research costs. No downloads, paid/cloud inference, uncharged warmups, or system changes."]
 for x in reference_checks:text.append(f"\n{x['engine']}: noisy selection/validation cells {x['unstable_selection_cells']}/{x['unstable_validation_cells']}; quality-failing selection/validation cells {x['quality_failing_selection_cells']}/{x['quality_failing_validation_cells']}. None were silently removed from the raw dataset.")
 text+=['','## Interpretation limits','','These tasks, domains and saved trajectories were already exposed and are now exhaustively measured for development analysis. They cannot become a new held-out cohort. Five seeds and three checkpoints are not15independent software systems. All timing is from one host and caches may be warm. The public ANN vectors and text corpus are small fixed inputs. Earlier-checkpoint opportunity does not demonstrate that an LLM would exploit it. No learned router, new method superiority, production benefit or journal readiness follows.','','Evidence: artifacts/study_v165/freeze.json binds the prospective protocol, configuration plans and frozen historical selections; results/v165_headroom/reference.freeze.json binds selection before validation. All768 acquisitions, reference IDs, per-cell timing/quality/noise, target mappings and figures are preserved. Analysis: scripts/report_headroom_v165.py; raw correctness/provenance replay: scripts/verify_headroom_v165.py.']
 (ROOT/'reports/headroom_v165.md').write_text('\n'.join(text)+'\n')
 plt.rcParams['svg.hashsalt']='headroom-v165';fig,axs=plt.subplots(1,2,figsize=(11,4),sharey=True);fig.subplots_adjust(left=.1,right=.98,top=.76,bottom=.18,wspace=.18)
 prefix=[r for r in rows if r['kind']=='prefix'];lo=min(-5,min(100*x['headroom'] for x in prefix)-5);hi=max(20,max(100*x['headroom'] for x in prefix)+5)
 for ax,e in zip(axs,['ripgrep','hnswlib']):
  for seed in [11,23,37,53,71]:
   rr=sorted((r for r in prefix if r['engine']==e and r['seed']==seed),key=lambda r:r['checkpoint']);ax.plot([r['checkpoint'] for r in rr],[100*r['headroom'] for r in rr],marker='o',lw=1,alpha=.8,label=str(seed))
  bad=[r for r in prefix if r['engine']==e and not r['stable_quality_comparison']];ax.scatter([r['checkpoint'] for r in bad],[100*r['headroom'] for r in bad],marker='x',s=100,linewidths=2,color='black',zorder=5)
  ax.axhline(0,color='gray',lw=.8);ax.axhline(10,color='gray',ls=':');ax.set_xticks([4,7,10]);ax.set_ylim(lo,hi);ax.set_title(e);ax.set_xlabel('Already acquired prefix labels');ax.grid(axis='y',alpha=.2)
 axs[0].set_ylabel('Observed improvement to reference (%)');axs[1].legend(title='Saved seed',fontsize=7,frameon=False);fig.suptitle('Development headroom: selected reference, fresh validation\nSame saved trajectories; black cross marks an unstable comparison');fig.savefig(O/'prefix_headroom.png',dpi=160,metadata={'Software':'V165'});fig.savefig(O/'prefix_headroom.svg',metadata={'Date':None});plt.close(fig)
 fig,axs=plt.subplots(1,2,figsize=(10,4));fig.subplots_adjust(left=.09,right=.97,top=.78,bottom=.18,wspace=.3)
 for ax,e in zip(axs,['ripgrep','hnswlib']):
  rr=[x for x in selection if x['engine']==e];xs=[x['median'] for x in rr];ys=[v[e,x['row_id']]['median'] for x in rr];ax.scatter(xs,ys,s=16,color='#176d8c',alpha=.65);c=next(x for x in reference_checks if x['engine']==e);ax.scatter([c['selection_median']],[c['validation_median']],marker='*',s=100,color='#b95c2d',label='Selected reference');bounds=[min(xs+ys)*.95,max(xs+ys)*1.05];ax.plot(bounds,bounds,ls=':',color='gray');ax.set_title(e);ax.set_xlabel('Selection median (seconds)');ax.set_ylabel('Validation median (seconds)');ax.legend(fontsize=7,frameon=False)
 fig.suptitle('All 64 settings/application: selection separated from validation');fig.savefig(O/'selection_validation.png',dpi=160,metadata={'Software':'V165'});fig.savefig(O/'selection_validation.svg',metadata={'Date':None});plt.close(fig);print(json.dumps({'collection':coll,'references':reference_checks,'prefix_summary':summaries},indent=2))
if __name__=='__main__':main()
