"""Read-only analysis of measured paired application outcomes; no policy fitting."""
import json,math,statistics
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
ROOT=Path(__file__).resolve().parents[1];A=ROOT/'artifacts/study_v163';O=ROOT/'results/v163_native';M=ROOT/'results/v163_models'
MODELS=['smollm3_3b','qwen3_8b'];ENGINES=['ripgrep','hnswlib'];CONTROLS=['sequential_3nn','adaptive_neighbor','gp_ei','random_full','random_proposal']
def read(p):return json.loads(p.read_text())
def lines(p):return [json.loads(x) for x in p.read_text().splitlines()]
def write(p,v):p.write_text(json.dumps(v,indent=2,allow_nan=False)+'\n')
def summaries(rows,validations,acquisitions):
 arms={}
 for r in rows:
  vv=[x['value'] for x in validations if x['case']==r['case'] and x['arm']==r['arm']];assert len(vv)==3
  median=statistics.median(vv);mad=statistics.median(abs(x-median) for x in vv)/median;ms=[x for x in acquisitions if x['case']==r['case'] and x['arm']==r['arm'] and x['phase']=='validation'];assert len(ms)==3
  arms[r['case'],r['arm']]={**r,'validation_values':vv,'median':median,'relative_mad':mad,'quality_feasible':all(x['status']=='correct' for x in ms),'minimum_recall_or_exact_quality':min(x['measurement']['quality'] for x in ms),'stable':mad<=.05,'above_floor':median>=.01}
 cases=[]
 for model in MODELS:
  for key in sorted({r['case'] for r in rows}):
   a=arms[key,model];g={};wins={};same={}
   for control in CONTROLS:
    b=arms[key,control];g[control]=(b['median']-a['median'])/b['median'];same[control]=a['row_id']==b['row_id'];wins[control]=g[control]>.1 and not same[control] and all(x['stable'] and x['quality_feasible'] and x['above_floor'] for x in [a,b])
   cases.append({'case':key,'engine':a['engine'],'model':model,'gains':g,'same_configuration':same,'robust_practical_wins':wins,'joint_robust_win':all(wins[c] for c in ['sequential_3nn','adaptive_neighbor','gp_ei'])})
 return arms,cases
def main():
 assert read(O/'completion.json')['acquisitions']==800;acq=[read(O/'acquisitions'/f'{i:03d}.json') for i in range(1,801)];arms,cases=summaries(read(O/'selections.json'),lines(O/'validation.jsonl'),acq);decisions=read(A/'decisions.json')['rows'];modelcost={};policies=[]
 for model in MODELS:
  ledger=read(M/model/'ledger.json');rr=lines(M/model/'responses.jsonl');starts=lines(M/model/'generation_starts.jsonl');lookup={r['key']:r for r in rr}
  used={k:sum(r['response'][k] for r in rr if type(r['response'].get(k)) is int) for k in ['tokens_evaluated','tokens_predicted']};unknown={k:len(starts)-sum(type(r['response'].get(k)) is int for r in rr) for k in used}
  modelcost[model]={'ledger':ledger,'responses':len(rr),'observed_usage':used,'unknown_usage_requests':unknown,'request_wall_seconds':sum(r['wall_seconds'] for r in rr)}
  ds=[d for d in decisions if d['model']==model];names=list(ds[0]['policies'])+['rank_expected_adaptation','hindsight_oracle']
  for name in names:
   rows=[]
   for d in ds:
    key=d['case'];case=next(c for c in cases if c['case']==key and c['model']==model);g=case['gains']['sequential_3nn'];prob=d['rank_expected_call'] if name=='rank_expected_adaptation' else (float(g>0) if name=='hindsight_oracle' else float(d['policies'][name]))
    prefix=sum(x['collection_seconds'] for x in acq if x['case']==key and x['phase']=='prefix');bc={b:sum(x['collection_seconds'] for x in acq if x['case']==key and x['arm']==b) for b in ['sequential_3nn',model]};request=lookup.get(key);rt=request['wall_seconds'] if request else None
    proxy=prefix+(1-prob)*bc['sequential_3nn']+prob*bc[model]+(prob*rt if rt is not None else 0)
    rows.append({'case':key,'engine':d['engine'],'call_probability':prob,'gain':prob*g,'deployment_collection_proxy_seconds':proxy if rt is not None or prob==0 else None})
   means={e:statistics.mean(r['gain'] for r in rows if r['engine']==e) for e in ENGINES};policies.append({'model':model,'policy':name,'calls_or_expected_calls':sum(r['call_probability'] for r in rows),'group_mean_gains':means,'equal_group_mean_gain':statistics.mean(means.values()),'deployment_configuration_evaluations':200,'deployment_native_invocations':600,'collection_time_proxy_seconds':sum(r['deployment_collection_proxy_seconds'] for r in rows) if all(r['deployment_collection_proxy_seconds'] is not None for r in rows) else None,'rows':rows})
 native={'configuration_outcomes':800,'native_workload_invocations':sum(x['measurement']['native_invocations'] for x in acq),'quality_feasible':sum(x['status']=='correct' for x in acq),'quality_penalties':sum(x['status']=='quality_penalty' for x in acq),'subprocess_collection_seconds':sum(x['collection_seconds'] for x in acq),'native_objective_seconds':sum(x['measurement']['objective_seconds'] for x in acq),'end_to_end_seconds':read(O/'completion.json')['seconds'],'minimum_ann_recall':min(x['measurement']['quality'] for x in acq if x['engine']=='hnswlib')}
 result={'cases':cases,'arms':list(arms.values()),'policies':policies,'model_costs':modelcost,'actual_collection':native};write(O/'comparison.json',result)
 plt.rcParams['svg.hashsalt']='v163';fig,axes=plt.subplots(1,2,figsize=(10,4),sharey=True);fig.subplots_adjust(left=.09,right=.98,bottom=.25,top=.77,wspace=.3)
 vals=[100*c['gains']['sequential_3nn'] for c in cases];axes[0].set_ylim(min(-15,math.floor(min(vals)/10)*10-5),max(15,math.ceil(max(vals)/10)*10+5))
 for ax,e in zip(axes,ENGINES):
  for mi,m in enumerate(MODELS):
   ys=[100*c['gains']['sequential_3nn'] for c in cases if c['engine']==e and c['model']==m];ax.scatter([mi+(k-2)*.06 for k in range(5)],ys,s=32,color=['#156e91','#b55d2d'][mi])
  ax.axhline(0,color='gray',lw=.8);ax.axhline(10,color='gray',lw=.8,ls=':');ax.set_xticks([0,1],['SmolLM3-3B','Qwen3-8B']);ax.set_title(e);ax.set_ylabel('Gain vs sequential 3NN (%)');ax.grid(axis='y',alpha=.2)
 fig.suptitle('Real-input application workloads: fresh validation\nFive seeds per family; positive values favor the local model',fontsize=11);fig.savefig(O/'paired_gains.png',dpi=160,metadata={'Software':'V163'});fig.savefig(O/'paired_gains.svg',metadata={'Date':None});plt.close(fig)
 text=['# V163: paired native application study','','The study is complete on two application lineages using real public input: ripgrep code analytics over CPython source, and hnswlib indexing/querying Optdigits vectors. Workload design was exposed by feasibility. This is a prospective paired comparison after feasibility, not an untouched production cohort or a journal-readiness certificate.','','## What ran','',f"**800 configuration-outcome evaluations**, **{native['native_workload_invocations']} native workload invocations**, **20 real local-model starts**, and **70 B20 arms**. Ten saved prefixes (five seeds per family) were cloned into five classical controls and two model continuations. Each arm had ten shared prefix evaluations, seven new configurations and three fresh incumbent validations. A ripgrep outcome times one fixed bundle of five distinct queries; individual-query timings are not measured or supplied as extra labels.",'','## Measured results','','Positive gain means a lower median fresh-validation utility. ANN utility requires at least95% tie-aware recall; otherwise the declared20second penalty applies. A robust joint win requires >10% gain over sequential, adaptive and GP-EI, different configuration IDs, all validations quality-feasible, MAD<=5% and both medians>=10ms.','','| Application | Model | Mean gain vs sequential | vs adaptive | vs GP-EI | Joint robust wins |','|---|---|---:|---:|---:|---:|']
 for e in ENGINES:
  for m in MODELS:
   cs=[c for c in cases if c['engine']==e and c['model']==m];gg=[100*statistics.mean(c['gains'][b] for c in cs) for b in ['sequential_3nn','adaptive_neighbor','gp_ei']];text.append(f"| {e} | {m} | {gg[0]:+.3f}% | {gg[1]:+.3f}% | {gg[2]:+.3f}% | {sum(c['joint_robust_win'] for c in cs)}/5 |")
 text+=['',f"Quality-feasible acquisitions: {native['quality_feasible']}/800; quality penalties: {native['quality_penalties']}. Minimum observed ANN recall: {100*native['minimum_ann_recall']:.3f}%. Validation cells above5% MAD: {sum(not a['stable'] for a in arms.values())}/70; below10ms: {sum(not a['above_floor'] for a in arms.values())}/70. Model/sequential pairs selecting the same setting: {sum(c['same_configuration']['sequential_3nn'] for c in cases)}/20. These flags do not remove outcomes from the unfiltered mean. All five classical controls and individual gains remain in comparison.json.",'','## Frozen routing policies','','Historical benefit/uncertainty models were transported unchanged; no threshold was fitted on these applications. Pre-continuation features and decisions were saved and hashed. BORA/rank rules remain checkpoint adaptations of source methods, not full original implementations. Rank expectation is a mathematical counterfactual average over real measured outcomes. The hindsight oracle is not deployable.','','| Model | Policy | Calls or expected calls / 10 | Equal-family mean gain vs never |','|---|---|---:|---:|']
 for p in policies:text.append(f"| {p['model']} | {p['policy']} | {p['calls_or_expected_calls']:.2f} | {100*p['equal_group_mean_gain']:+.3f}% |")
 text+=['','## Collection cost versus deployment estimate','',f"Actual paired native collection: {native['subprocess_collection_seconds']:.3f} subprocess-seconds, including {native['native_objective_seconds']:.3f} objective-seconds. End-to-end paired stage: {native['end_to_end_seconds']:.3f}s. Prior80 feasibility outcomes/160 native invocations, source retrieval, compilation and correctness-reference work are additional research costs. Both continuations, controls and validation remain charged.",'']
 for m,v in modelcost.items():
  l=v['ledger'];text.append(f"- {m}: {l['generation_requests']} starts/{v['responses']} responses; observed input/output tokens {v['observed_usage']['tokens_evaluated']}/{v['observed_usage']['tokens_predicted']}; unknown-usage request counts {v['unknown_usage_requests']}; request time {v['request_wall_seconds']:.3f}s; total model-stage time {l['stage_seconds']:.3f}s; peak RSS {l['peak_server_rss_bytes']} bytes; server exit {l['server_exit_code']}.")
 text+=['','For ten-case deployment, one selected arm per case uses200 configuration evaluations and600 native invocations (five ripgrep cases ×100 invocations plus five ANN cases ×20). Model request count depends on the policy. comparison.json gives a retrospective selected-branch time proxy using measured branch/request durations; cold-start time is separate. It is not a measured deployment, invoice or energy estimate. No paid/cloud inference or new model download occurred.','','## Scope and limitations','','Only two independent implementation groups are added. Seeds, query types and vectors are not independent systems. Inputs are real public data but these tasks are not production deployments. Source/reference reads warm caches; no cache flushing or system changes were used. Timing is from one machine. Approximate-neighbor quality is task-specific, and the historical router target used20 search evaluations versus the present17+3 design. Quantized model families, constrained batch proposals, projection, public-data familiarity, budget and workload-design exposure limit generalization. No population significance, equivalence, full prior-method replication or journal acceptance follows.','','Failed V161 admission and the separately frozen V162 repair are retained. GNU sort was excluded after an alias audit found prior measured history. All observed outcomes belong to development/exploratory evidence for any subsequent protocol; do not retune here and call the same cases held out. The next priority is independent replication and broader prospectively selected application evidence, with this comparison set fixed.','','Evidence: artifacts/study_v163 contains frozen inputs, prefixes/prompts, model pins and router decisions. results/v163_native contains all800 acquisitions, branch states, fixed selections,210 validations, aggregates and figures. results/v163_models contains raw prompts/responses, starts, token accounting, capacity checks and process-exit receipts. Safe report replay: .venv/bin/python scripts/report_apps_v163.py; collectors are create-once.']
 (ROOT/'reports/apps_v163.md').write_text('\n'.join(text)+'\n');print(json.dumps({'collection':native,'joint_robust_wins':{m:sum(c['joint_robust_win'] for c in cases if c['model']==m) for m in MODELS},'models':modelcost},indent=2))
if __name__=='__main__':main()
