"""Deterministic descriptive analysis; no new acquisition or threshold fitting."""
import json,statistics,sys
from fractions import Fraction
from collect_smollm_v47 import ROOT,read,write
from spark_v144 import A,O,CONTROLS,TASKS

def gain(a,b):return float((Fraction(str(a))-Fraction(str(b)))/Fraction(str(a)))
def main():
 jobs=read(A/'jobs.json');models=read(ROOT/'configs/study_v144.json')['model_order'];decisions={r['key']:r for r in read(A/'decisions.json')['rows']};cases=[];stats={}
 for model in models:
  for j in jobs:
   arm=read(O/'models'/f"{model}_{j['key']}.json");base={k:read(O/'classical'/f"{j['key']}_{k}.json")['target'] for k in CONTROLS};p=read(ROOT/j['prefix']);prefix=min(y[0] for y in p['labels']);gains={k:gain(v,arm['target']) for k,v in base.items()};d=decisions[j['key']]
   policies={k:bool(v) for k,v in d.items() if k in ['benefit','uncertainty','random_matched_rate']};policies.update(never=False,always=True);pol={k:{'escalate':v,'target':arm['target'] if v else base['sequential_3nn'],'gain':gains['sequential_3nn'] if v else 0.,'harmful_call':v and gains['sequential_3nn']<-.01,'missed_useful_call':not v and gains['sequential_3nn']>.01} for k,v in policies.items()}
   cases.append({'model':model,'key':j['key'],'app':j['app'],'seed':j['seed'],'system_group':'spark','prefix_best':prefix,'model_target':arm['target'],'controls':base,'gains':gains,'prefix_gain':gain(prefix,arm['target']),'fallback':arm['fallback'],'policies':pol,'hindsight_gain_diagnostic':max(0.,gains['sequential_3nn'])})
  cs=[r for r in cases if r['model']==model];sub=ROOT/'results/v144_models'/model;responses=[json.loads(s) for s in (sub/'responses.jsonl').read_text().splitlines()];ledger=read(sub/'ledger.json');diags=[d for p in (O/'models').glob(model+'_*.json') for d in read(p)['projection']]
  stats[model]={'cases':len(cs),'controls':{k:{'mean_gain':statistics.mean(r['gains'][k] for r in cs),'wins':sum(r['gains'][k]>0 for r in cs),'ties':sum(r['gains'][k]==0 for r in cs),'losses':sum(r['gains'][k]<0 for r in cs),'practical_wins':sum(r['gains'][k]>.01 for r in cs),'practical_harm':sum(r['gains'][k]<-.01 for r in cs)} for k in CONTROLS},'workloads':{app:{k:statistics.mean(r['gains'][k] for r in cs if r['app']==app) for k in CONTROLS} for app,_,_ in TASKS},'joint_practical_wins_sequential_adaptive':sum(r['gains']['sequential_3nn']>.01 and r['gains']['adaptive_neighbor']>.01 for r in cs),'prefix_improvements':sum(r['prefix_gain']>0 for r in cs),'hindsight_mean_gain_diagnostic':statistics.mean(r['hindsight_gain_diagnostic'] for r in cs),'fallbacks':sum(r['fallback'] for r in cs),'policies':{k:{'calls':sum(r['policies'][k]['escalate'] for r in cs),'mean_gain':statistics.mean(r['policies'][k]['gain'] for r in cs),'harmful_calls':sum(r['policies'][k]['harmful_call'] for r in cs),'missed_useful_calls':sum(r['policies'][k]['missed_useful_call'] for r in cs)} for k in cs[0]['policies']},'projection':{'count':len(diags),'nonzero':sum(d['distance']>0 for d in diags),'repeated':sum(d['repeated_proposal'] for d in diags),'matches_prefix':sum(d['matches_prefix'] for d in diags)},'cost':{**ledger,'generated_tokens':sum(r['response']['tokens_predicted'] for r in responses if isinstance(r['response'].get('tokens_predicted'),int)),'prefill_tokens':sum(r['response']['tokens_evaluated'] for r in responses if isinstance(r['response'].get('tokens_evaluated'),int)),'missing_token_records':sum(not isinstance(r['response'].get('tokens_predicted'),int) or not isinstance(r['response'].get('tokens_evaluated'),int) for r in responses),'request_wall_seconds':sum(r['wall_seconds'] for r in responses)}}
 out={'scope':'One prospective Spark family, five fixed workloads, five repeated seeds; descriptive and representation-adapted','cases':cases,'models':stats,'collection':read(O/'completion.json'),'classical_collection':read(O/'classical_summary.json')};write(O/'comparison.json',out)
 lines=['# V144 prospective Spark recorded-data result','',out['scope']+'. No independent-family confidence interval or Q2-readiness claim. Spark runs were recorded by source authors; this batch did not execute Spark.','', '| Model | Mean gain vs sequential | Mean gain vs adaptive | >1% wins over both | Real requests | Generated tokens |','|---|---:|---:|---:|---:|---:|']
 for model,s in stats.items():lines.append(f"| {model} | {100*s['controls']['sequential_3nn']['mean_gain']:.4f}% | {100*s['controls']['adaptive_neighbor']['mean_gain']:.4f}% | {s['joint_practical_wins_sequential_adaptive']}/25 | {s['cost']['generation_requests']} | {s['cost']['generated_tokens']} |")
 lines+=['','Positive gain favors the LLM. Equal workload weighting equals the case mean here because every workload has five seeds. No models, cases or failures were removed based on outcomes.','', '| Model / workload | Sequential | Adaptive | Fixed neighbor | Random rows | Random prototypes |','|---|---:|---:|---:|---:|---:|']
 for model,s in stats.items():
  for app,g in s['workloads'].items():lines.append('| '+model+' / '+app+' | '+' | '.join(f'{100*g[k]:.4f}%' for k in CONTROLS)+' |')
 lines+=['','## Frozen policies','', 'Thresholds come exclusively from V132 historical development families. Transferring this Qwen-trained controller to SmolLM is uncalibrated. Random escalation exactly matches the realized benefit-controller rate; all decisions preceded continuations.','', '| Model / policy | Calls /25 | Mean gain vs never | Harmful calls (<−1%) | Missed useful calls (>1%) |','|---|---:|---:|---:|---:|']
 for model,s in stats.items():
  for k,v in s['policies'].items():lines.append(f"| {model} / {k} | {v['calls']} | {100*v['mean_gain']:.4f}% | {v['harmful_calls']} | {v['missed_useful_calls']} |")
  lines+=['',f"{model}: hindsight oracle mean gain {100*s['hindsight_mean_gain_diagnostic']:.4f}% (non-deployable reference); {s['prefix_improvements']}/25 prefix improvements; {s['fallbacks']} fallbacks. Projection diagnostics: {s['projection']}.",'']
 lines+=['## Cost and limits','',f"Actual research collection: {out['collection']['total_acquisitions']} charged outcomes (250 shared prefixes,1250 control and500 model continuations),175 B20 arms; {out['collection']['total_collection_seconds']:.3f}s from prefix start through final acquisition. Classical collection took {out['classical_collection']['seconds']:.3f}s. No paid/cloud inference or new Spark executions.",'']
 for model,s in stats.items():
  c=s['cost'];lines.append(f"{model}: {c['generation_requests']} requests, {c['retries']} retries, {c['generated_tokens']} generated/{c['prefill_tokens']} prefill tokens, {c['missing_token_records']} missing-usage records; {c['stage_seconds']:.3f}s lifecycle, {c['request_wall_seconds']:.3f}s request wall, {c.get('startup_seconds',0):.3f}s startup, peak sampledRSS {c['peak_server_rss_bytes']}bytes. Server exit {c['server_exit_code']}; stop reason {c.get('stop_reason')}.")
 lines+=['','Deployment scenario uses only the chosen policy continuation after B10: one model request per escalation,10new recorded outcomes either way, plus amortized model loading. Actual collection deliberately paid for both models and all controls. No source-duration-to-dollar/native-runtime/energy conversion.','', 'Limitations: one independent family; historical source sampling and failure/correctness/noise are incompletely certified; a finite observed candidate support; numerical bounds are transductive feature-only; ten-level prototype grid and mixed-distance projection differ from V141; public-data contamination unknown; model blocks confound runtime with order/cache/temperature; these are complete model treatments, not parameter-count causality. Positive and negative workload/seed exceptions remain in comparison.json. Further tuning requires a new exploratory protocol and new independent evaluation.','', 'Reproduce: `.venv/bin/python scripts/verify_spark_v144.py`; `MPLCONFIGDIR=/tmp/mpl-v144 .venv/bin/python scripts/report_spark_v144.py`. See protocol_v144.md,source_audit_v143.md and artifacts/study_v144 for source pins,pre-decision seals,prompts and tests.']
 (ROOT/'reports/spark_v144.md').write_text('\n'.join(lines)+'\n')
 import matplotlib;matplotlib.use('Agg')
 import matplotlib.pyplot as plt
 plt.rcParams['svg.hashsalt']='v144';fig,axes=plt.subplots(1,2,figsize=(11,4),sharey=True)
 for ax,mode in zip(axes,['sequential_3nn','adaptive_neighbor']):
  for i,(model,s) in enumerate(stats.items()):ax.bar([j+(i-.5)*.34 for j in range(5)],[100*s['workloads'][app][mode] for app,_,_ in TASKS],width=.34,label=model)
  ax.axhline(0,color='black',lw=.8);ax.axhline(1,color='gray',ls=':',lw=.8);ax.axhline(-1,color='gray',ls=':',lw=.8);ax.set_xticks(range(5),[a for a,_,_ in TASKS],rotation=20);ax.set_title('LLM gain vs '+mode);ax.set_ylabel('Mean relative gain (%)');ax.grid(axis='y',alpha=.2)
 axes[0].legend(fontsize=8);fig.suptitle('One Spark family • five workloads × five seeds • recorded outcomes');fig.tight_layout();fig.savefig(O/'comparison.png',dpi=160);fig.savefig(O/'comparison.svg',metadata={'Date':None});plt.close(fig)
 print(json.dumps({m:{k:s[k] for k in ['controls','joint_practical_wins_sequential_adaptive','policies']} for m,s in stats.items()},indent=2))
if __name__=='__main__':main()
