"""Predeclared normal-adapter, cheap-control and loss-ablation report."""
import json,statistics
from table_check_v121 import ROOT,read,write,MODES
from escalation.core import State
from escalation.transfer_v41 import best
OUT=ROOT/'results/v121_report'
def main():
    s=read(ROOT/'results/v121_analysis/summary.json');assert s['complete'];normal=[r for r in s['cases'] if r['condition']=='normal'];blind=[r for r in s['cases'] if r['condition']=='loss_blind'];assert len(normal)==len(blind)==5
    contrasts={m:{'mean':statistics.mean(r['gains'][m] for r in normal),'wins':sum(r['gains'][m]>1e-12 for r in normal),'ties':sum(abs(r['gains'][m])<=1e-12 for r in normal),'losses':sum(r['gains'][m]<-1e-12 for r in normal),'valid_5pct_wins':sum(r['gains'][m]>=.05 and not r['fallback'] for r in normal)} for m in MODES}
    pairs=[]
    for n,b in zip(normal,blind):
        assert n['base_key']==b['base_key'];nc=read(ROOT/f"results/v121_qwen/choices/{n['key']}.json");bc=read(ROOT/f"results/v121_qwen/choices/{b['key']}.json")
        pairs.append({'seed':n['optimization_seed'],'normal_ids':nc['selected_ids'],'blind_ids':bc['selected_ids'],'same_ordered_ids':nc['selected_ids']==bc['selected_ids'],'same_configuration_set':set(n['selected_rows'])==set(b['selected_rows']),'normal_first10':nc['selected_ids']==list('0123456789'),'blind_first10':bc['selected_ids']==list('0123456789'),'normal_target':n['target'],'blind_target':b['target'],'normal_fallback':n['fallback'],'blind_fallback':b['fallback']})
    pc=read(ROOT/'results/v121_classical/policy_precommit.json');policies=[]
    for target,maskkey,controls in [('primary','masks',MODES[:2]),('first10','first10_masks',('presentation_first10',))]:
        for m in controls:
            masks={**pc[maskkey],'hindsight_oracle_diagnostic':[r['gains'][m]>0 for r in normal]}
            for name,mask in masks.items():
                selected=[r for r,on in zip(normal,mask) if on]
                policies.append({'training_target':target,'control':m,'policy':name,'escalations':sum(mask),'mean_gain':statistics.mean(r['gains'][m] if on else 0 for r,on in zip(normal,mask)),'missed_valid_5pct_wins':sum(not on and not r['fallback'] and r['gains'][m]>=.05 for r,on in zip(normal,mask)),'harmful_5pct_escalations':sum(on and r['gains'][m]<=-.05 for r,on in zip(normal,mask)),'deployment_requests':10*sum(mask),'observed_requests':sum(r['charged_requests'] for r in selected),'selected_failures':sum(r['fallback'] for r in selected)})
    # The free V120 control is replayable because every selected row equals the rule.
    storm=[]
    for old in read(ROOT/'results/v120_analysis/summary.json')['cases']:
        p=read(ROOT/f"results/v119_classical/prefixes/{old['key']}.json");arm=read(ROOT/f"results/v120_analysis/arms/{old['key']}.json");ids=[p['pool']['mapping'][i] for i in '0123456789'];assert ids==arm['state']['ids'][10:]==old['selected_rows'];assert best(State(**arm['state']),'-')==old['target'];storm.append({'key':old['key'],'exact_ordered_row_match':True,'gain_against_first10':0.})
    historical=read(ROOT/'results/v91_analysis/cases.json');allrows=[{'family':r['system_group'],'role':'exposed_development','gains':{m:r['gains'][m] for m in ('batch_3nn','full_sequential_3nn','presentation_first10')}} for r in historical]
    allrows += [{'family':'storm','role':'exploratory_development','gains':{'batch_3nn':r['gains']['batch_3nn'],'full_sequential_3nn':r['gains']['full_sequential_3nn'],'presentation_first10':0.}} for r in read(ROOT/'results/v120_analysis/summary.json')['cases']]
    allrows += [{'family':'mongodb','role':'prospective_test','gains':{m:r['gains'][m] for m in ('batch_3nn','full_sequential_3nn','presentation_first10')}} for r in normal]
    families={g:{'role':next(r['role'] for r in allrows if r['family']==g),'means':{m:statistics.mean(r['gains'][m] for r in allrows if r['family']==g) for m in ('batch_3nn','full_sequential_3nn','presentation_first10')}} for g in sorted({r['family'] for r in allrows})}
    primary=('batch_3nn','full_sequential_3nn','presentation_first10');joint=sum(not r['fallback'] and all(r['gains'][m]>=.05 for m in primary) for r in normal)
    result={'scope':'One prospective MongoDB family; five paired seeds; frozen V120 adapter; seven exposed development families; no broad generalization test','contrasts':contrasts,'joint_5pct_wins_against_three':joint,'descriptive_criterion_met':joint>0 and all(contrasts[m]['mean']>0 for m in primary),'ablation_pairs':pairs,'policies':policies,'v120_first10_replay':storm,'eight_family_descriptive_context_not_pooled_holdout':families,'collection':{'real_model_requests':s['new_model_requests'],'recorded_acquisitions':s['actual_classical_acquisitions']+s['actual_new_llm_acquisitions'],'generated_tokens':s['actual_generated_tokens'],'prefill_tokens':s['actual_prefill_tokens'],'lifecycle_seconds':s['ledger']['stage_seconds'],'peak_rss_bytes':s['ledger']['peak_server_rss_bytes'],'normal_fallbacks':sum(r['fallback'] for r in normal),'blind_fallbacks':sum(r['fallback'] for r in blind),'spend_usd':0,'source_download_bytes':read(ROOT/'artifacts/sources/v121/manifest.json')['total_bytes']}}
    write(OUT/'summary.json',result)
    text=['# V121: does the fixed adapter add value beyond free candidate ordering?','',
      'The earlier WordCount result needs an important qualification: all five V120 continuations selected candidate IDs0–9 in presentation order. Replaying those exact already-acquired configurations gives the same outcome with a zero-model first-ten rule. The8.07%/7.60% gains over the original controls were real, but did not establish incremental value from calling an LLM. No new objective values were needed for this identity proof. The original failures, successes and model costs remain preserved.','',
      'V121 prospectively evaluates the fixed constrained adapter on the owner MongoDB table. Software/workload and runtime direction are documented; journal/security semantics are held fixed, leaving270 configurations. Five seeds are repetitions of one family, not five systems. A new matched controller was fitted on all35 saved cases from seven other families before any MongoDB target was acquired. No threshold was changed after the test.','',
      '## Normal-adapter result','',
      '| Control | Mean relative gain | Wins/ties/losses | Valid ≥5% wins |','|---|---:|---:|---:|']
    for m,c in contrasts.items():text.append(f"| {m} | {100*c['mean']:.3f}% | {c['wins']}/{c['ties']}/{c['losses']} | {c['valid_5pct_wins']}/5 |")
    text += ['',f"Joint ≥5% wins against batch3NN, sequential3NN and first-ten: **{joint}/5**. The predeclared descriptive criterion is **{'met' if result['descriptive_criterion_met'] else 'not met'}**. No confidence interval or significance claim from one test family.",'','## Paired loss-removal intervention','','The loss-blind condition replaces observed normalized losses with0.5; configurations, IDs, order, shortlist, instructions and decoding are held fixed. The shortlist itself was acquired-label-dependent, so this does not remove every possible source of performance information.','', '| Seed | Normal IDs | Loss-blind IDs | Same ordered IDs | Normal first-ten |','|---|---|---|---|---|']
    for p in pairs:text.append(f"| {p['seed']} | {''.join(p['normal_ids'])} | {''.join(p['blind_ids'])} | {p['same_ordered_ids']} | {p['normal_first10']} |")
    text += ['','Identical choices under this intervention demonstrate insensitivity to the supplied loss values for these particular prompts. They do not prove that the model cannot use observations elsewhere or isolate all internal mechanisms. Differing selections would be retained equally.','', '## Frozen routing result','','| Target / control | Policy | Escalations | Mean gain | Missed ≥5% wins |','|---|---|---:|---:|---:|']
    for p in policies:
        if p['policy'] in ['never','always','benefit','uncertainty','random_development_benefit','random_development_uncertainty']:text.append(f"| {p['training_target']} / {p['control']} | {p['policy']} | {p['escalations']}/5 | {100*p['mean_gain']:.3f}% | {p['missed_valid_5pct_wins']} |")
    text += ['', 'Two model-matched regressions predict (a) the minimum gain against the two original controls and (b) gain against the free first-ten rule. Standardization/coefficients/thresholds were fitted only on development groups; all seven families were retained. Thresholds optimize group-mean selected gain with fewer-call tie breaks, not a fabricated dollar penalty. Leave-family-out predictions select development thresholds; there is still only one prospective test family. All matched-rate diagnostics and hindsight rows are in summary.json.','', '## Same-adapter historical context (not a pooled held-out result)','','| Family | Role | Batch gain | Sequential gain | First-ten gain |','|---|---|---:|---:|---:|']
    for g,f in families.items():text.append(f"| {g} | {f['role']} | "+' | '.join(f"{100*f['means'][m]:.3f}%" for m in primary)+' |')
    cost=result['collection'];text += ['', '## Cost, reliability and reproducibility','',f"Actual new collection: {cost['real_model_requests']} real requests, {cost['recorded_acquisitions']} recorded acquisitions (50prefix+250classical+100normal/blind), {cost['generated_tokens']} generated tokens, {cost['prefill_tokens']} reported prefill tokens, {cost['lifecycle_seconds']:.3f}s model lifecycle, peak sampled RSS{cost['peak_rss_bytes']:,}bytes. Normal/blind fallbacks: {cost['normal_fallbacks']}/{cost['blind_fallbacks']}. New source bodies: {cost['source_download_bytes']:,}bytes. No retries, paid/cloud calls or system installs; zero external spend. The raw ledger preserves startup, HTTP count and caps.",'',
      'A deployed policy uses one selected branch after its prefix; ten requests per model escalation versus zero for first-ten. The blind intervention and all counterfactual branches are research cost, not deployment requirements. Historical training collection is reused, not free. Native software runtime and dollars are unmeasured; no production cost-saving claim follows.','',
      'Source documents, Git-object checks and feature-only manifest: artifacts/sources/v121/ and data/manifest_v121.json. Frozen protocol: reports/protocol_v121.md. Matched development fits: results/v121_router/. Classical prefixes/controls/masks: results/v121_classical/. Raw real inference: results/v121_qwen/. Acquisitions: results/v121_analysis/. Replays/tests: artifacts/study_v121/. Regenerate this report/figure with scripts/report_replication_v121.py.','',
      '## Limits and next research priority','',
      'This is original recorded-label optimization, not a new MongoDB benchmark run. The workload has a custom configuration not fully archived here; repeated-run dispersion is documented but per-attempt correctness and failure linkage remain unverified. The fixed partition restricts external validity. Pretraining contamination is unknown. ExaStencils was downloaded for audit but excluded without reading performance values because workload/version and performance-stage identity remain unresolved. No new stronger V52 admission is claimed.','',
      'The immediate research priority is an adapter that demonstrates incremental value over cheap ordering controls on development families, then a separately frozen evaluation on additional independent families. Avoid further positive-outcome hunting with the unchanged decoder. A useful learned router cannot be established by predicting gains obtainable without inference. Preserve null results and remaining small genuine model advantages in the historical data. Q2 readiness is not established by these traces alone.']
    (ROOT/'reports/replication_v121.md').write_text('\n'.join(text)+'\n')
    import matplotlib
    matplotlib.use('Agg');matplotlib.rcParams['svg.hashsalt']='replication-v121'
    import matplotlib.pyplot as plt
    fig,ax=plt.subplots(figsize=(8,4.5))
    for m in primary:ax.plot(range(5),[100*r['gains'][m] for r in normal],marker='o',label=m.replace('_',' '))
    ax.axhline(0,color='gray',lw=.8);ax.axhline(5,color='gray',ls=':');ax.set_xticks(range(5),[r['optimization_seed'] for r in normal]);ax.set_xlabel('Optimization seed — one held-out MongoDB family');ax.set_ylabel('Relative gain in recorded runtime (%)');ax.set_title('Frozen constrained Qwen adapter versus cheap controls');ax.legend(fontsize=8);ax.grid(alpha=.15);fig.tight_layout();fig.savefig(OUT/'comparison.png',dpi=160);fig.savefig(OUT/'comparison.svg',metadata={'Date':None});plt.close(fig)
    print(json.dumps({k:v for k,v in result.items() if k not in ['policies','eight_family_descriptive_context_not_pooled_holdout']},indent=2))
if __name__=='__main__':main()
