"""All-case descriptive projection report; no new model or target calls."""
import statistics,json
from table_check_v119 import ROOT,read,write

def main():
 s=read(ROOT/'results/v122_analysis/summary.json');assert s['complete'];rows=s['cases'];controls=list(rows[0]['gains']);contrasts={m:{'mean':statistics.mean(r['gains'][m] for r in rows),'wins':sum(r['gains'][m]>1e-12 for r in rows),'ties':sum(abs(r['gains'][m])<=1e-12 for r in rows),'losses':sum(r['gains'][m]<-1e-12 for r in rows)} for m in controls};primary=['batch_3nn','full_sequential_3nn','presentation_first10'];joint=sum(r['status']!='fallback' and all(r['gains'][m]>=.05 for m in primary) for r in rows)
 result={'scope':s['scope'],'contrasts':contrasts,'joint_5pct_wins':joint,'criterion_met':joint>0 and all(contrasts[m]['mean']>0 for m in primary),'fallbacks':sum(r['status']=='fallback' for r in rows),'proposals':sum(len(r['trace']) for r in rows),'projected':sum(t['projected'] for r in rows for t in r['trace']),'collision_alternatives':sum(t['closest_already_used'] for r in rows for t in r['trace']),'new_acquisitions':s['actual_new_acquisitions'],'new_model_requests':0,'historical_model_requests':5};write(ROOT/'results/v122_analysis/comparison.json',result)
 text=['# V122: development-only projection of real cached configuration strings','','All five original V119 responses were retained. They failed the original ID contract and remain failures in V119. Here a newly frozen parser interprets their literal configuration strings, validates each feature index, and projects by feature-only nominal distance onto the remaining saved20-candidate shortlist. Tie breaking follows the saved state order. This is an exploratory changed-parser adaptation on exposed WordCount prefixes, not another model sample or an independent test.','','| Control | Mean relative gain | Wins/ties/losses |','|---|---:|---:|']
 for m,c in contrasts.items():text.append(f"| {m} | {100*c['mean']:.3f}% | {c['wins']}/{c['ties']}/{c['losses']} |")
 text += ['',f"Joint≥5% wins against batch, sequential and first-ten: {joint}/5. Development screening criterion: {'met' if result['criterion_met'] else 'not met'}. Malformed/fallback cases: {result['fallbacks']}/5. Among{result['proposals']} real proposals, {result['projected']} required a nonzero-distance projection and{result['collision_alternatives']} chose an alternative because the closest row was already selected. All mapping traces are saved before objective acquisition.",'','| Seed | Target | Batch gain | Sequential gain | First-ten gain |','|---|---:|---:|---:|---:|']
 for r in rows:text.append(f"| {r['seed']} | {r['target']:.6g} | {100*r['gains']['batch_3nn']:.3f}% | {100*r['gains']['full_sequential_3nn']:.3f}% | {100*r['gains']['presentation_first10']:.3f}% |")
 text += ['','Actual new cost:50 recorded acquisitions, zero model requests/downloads/spending; each logical branch is the original prefix10 plus continuation10. The five historical V119 real requests and300 generated tokens remain research cost. A hypothetical deployed adapter needs a real request per escalation; a cached replay is not free inference. No fabricated responses, repaired raw text, hidden-label projection or target-based candidate selection.','','The projection rule and selections were frozen before these new branch acquisitions. All five seeds/controls remain; no projection or threshold retuning followed the result. The same table was already exposed and the model/input format differs from the constrained adapter. Neither positive nor negative findings establish unseen-system routing, production reliability, a direct SNAP2 replication or journal readiness. Earlier V92/V93 results already show that unforced decoding alone is not a general cure. This diagnostic tests one different interpretation of preserved model outputs, not a universal solution.','','Evidence: reports/protocol_v122.md and .freeze.json; results/v122_projection/choices and selection_seal.json; results/v122_analysis/acquisitions.jsonl and arms; scripts/verify_cached_v122.py. Each cache key includes parser version, original request/response and prefix hash. Source/model/prompt provenance remains V119.']
 (ROOT/'reports/cached_projection_v122.md').write_text('\n'.join(text)+'\n');print(json.dumps(result,indent=2))
if __name__=='__main__':main()
