"""Outcome-only reporting after frozen selections; no collection or policy fitting."""
import json,math,statistics
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
ROOT=Path(__file__).resolve().parents[1];A=ROOT/'artifacts/study_v159';O=ROOT/'results/v159_native';M=ROOT/'results/v159_models'
MODELS=['smollm3_3b','qwen3_8b'];CONTROLS=['sequential_3nn','adaptive_neighbor','gp_ei','random_full','random_proposal']
def read(p):return json.loads(p.read_text())
def lines(p):return [json.loads(x) for x in p.read_text().splitlines()]
def write(p,v):p.write_text(json.dumps(v,indent=2,allow_nan=False)+'\n')
def gain(base,value):return (base-value)/base

def summaries(rows,validations,acquisitions):
 arms={}
 for r in rows:
  v=[x['value'] for x in validations if x['case']==r['case'] and x['arm']==r['arm']];assert len(v)==3
  q=statistics.median(v);mad=statistics.median([abs(x-q) for x in v])/q;measurements=[x for x in acquisitions if x['case']==r['case'] and x['arm']==r['arm'] and x['phase']=='validation'];assert len(measurements)==3
  arms[(r['case'],r['arm'])]={**r,'validation_values':v,'median':q,'relative_mad':mad,'correct_validation':all(x['status']=='correct' for x in measurements),'stable':mad<=.05}
 cases=[]
 for model in MODELS:
  for key in sorted({r['case'] for r in rows}):
   a=arms[key,model];g={};robust={};same={}
   for control in CONTROLS:
    b=arms[key,control];g[control]=gain(b['median'],a['median']);same[control]=a['row_id']==b['row_id'];robust[control]=g[control]>.1 and a['stable'] and b['stable'] and a['correct_validation'] and b['correct_validation'] and not same[control]
   cases.append({'case':key,'engine':a['engine'],'model':model,'median':a['median'],'relative_mad':a['relative_mad'],'gains':g,'same_configuration':same,'robust_practical_wins':robust,'joint_robust_win':all(robust[c] for c in ['sequential_3nn','adaptive_neighbor','gp_ei'])})
 return arms,cases

def main():
 assert read(O/'completion.json')['acquisitions']==800;acq=[read(O/'acquisitions'/f'{i:03d}.json') for i in range(1,801)];selections=read(O/'selections.json');vs=lines(O/'validation.jsonl');arms,cases=summaries(selections,vs,acq);decisions=read(A/'decisions.json')['rows'];models={};policies=[]
 for model in MODELS:
  ledger=read(M/model/'ledger.json');rr=lines(M/model/'responses.jsonl');starts=lines(M/model/'generation_starts.jsonl');lookup={r['key']:r for r in rr}
  tokens={k:sum(r['response'][k] for r in rr if type(r['response'].get(k)) is int) for k in ['tokens_predicted','tokens_evaluated']};unknown={k:len(starts)-sum(type(r['response'].get(k)) is int for r in rr) for k in tokens}
  models[model]={'ledger':ledger,'responses':len(rr),'usage_observed':tokens,'usage_unknown_requests':unknown,'request_wall_seconds':sum(r['wall_seconds'] for r in rr),'invalid_or_missing':sum(not (M/model/'scores'/f"{j['key']}.json").exists() or read(M/model/'scores'/f"{j['key']}.json")['status']!='valid' for j in read(A/'jobs.json'))}
  ds=[d for d in decisions if d['model']==model];ps=list(ds[0]['policies'])+['rank_expected_adaptation','hindsight_oracle'];cs=[c for c in cases if c['model']==model]
  for policy in ps:
   chosen=[]
   for d in ds:
    c=next(c for c in cs if c['case']==d['case']);g=c['gains']['sequential_3nn'];prob=d['rank_expected_call'] if policy=='rank_expected_adaptation' else (float(g>0) if policy=='hindsight_oracle' else float(d['policies'][policy]));key=d['case']
    prefix_cost=sum(x['collection_seconds'] for x in acq if x['case']==key and x['phase']=='prefix');branch_cost={b:sum(x['collection_seconds'] for x in acq if x['case']==key and x['arm']==b) for b in ['sequential_3nn',model]};req=lookup.get(key);reqtime=None if req is None else req['wall_seconds']
    est=prefix_cost+(1-prob)*branch_cost['sequential_3nn']+prob*branch_cost[model]+(prob*reqtime if reqtime is not None else 0)
    chosen.append({'case':key,'engine':d['engine'],'call_probability':prob,'gain':prob*g,'selected_collection_proxy_seconds':est if reqtime is not None or prob==0 else None})
   group={e:statistics.mean(x['gain'] for x in chosen if x['engine']==e) for e in ['cvc5','ortools']};p={'model':model,'policy':policy,'calls_or_expected_calls':sum(x['call_probability'] for x in chosen),'engine_mean_gains':group,'two_engine_mean_gain':statistics.mean(group.values()),'estimated_deployment_native_evaluations':200,'selected_collection_proxy_seconds':sum(x['selected_collection_proxy_seconds'] for x in chosen) if all(x['selected_collection_proxy_seconds'] is not None for x in chosen) else None,'rows':chosen};policies.append(p)
 comp={'cases':cases,'arms':[v for v in arms.values()],'model_costs':models,'policies':policies,'actual_collection':{'native_acquisitions':800,'native_correct':sum(x['status']=='correct' for x in acq),'native_timeout_penalties':sum(x['status']=='timeout_penalty' for x in acq),'native_collection_seconds':sum(x['collection_seconds'] for x in acq),'native_solve_seconds':sum(x['measurement']['solve_seconds'] for x in acq),'completion_seconds':read(O/'completion.json')['seconds'],'new_model_requests':sum(v['ledger']['generation_requests'] for v in models.values())}}
 write(O/'comparison.json',comp)
 plt.rcParams['svg.hashsalt']='v159';fig,axes=plt.subplots(1,2,figsize=(10,3.8),sharey=True);fig.subplots_adjust(left=.085,right=.98,bottom=.25,top=.78,wspace=.35)
 for ax,e in zip(axes,['cvc5','ortools']):
  for mi,m in enumerate(MODELS):
   ys=[100*c['gains']['sequential_3nn'] for c in cases if c['model']==m and c['engine']==e];ax.scatter([mi+(k-2)*.055 for k in range(5)],ys,s=30,label=m,color=['#156e91','#b55d2d'][mi])
  ax.axhline(0,color='gray',linewidth=.8);ax.axhline(10,color='gray',linestyle=':',linewidth=.8);ax.set_xticks([0,1],['SmolLM3-3B','Qwen3-8B']);ax.set_title(e);ax.set_ylabel('Gain vs sequential 3NN (%)');ax.grid(axis='y',alpha=.2)
 axes[0].set_ylim(min(-100,math.floor(min(100*c['gains']['sequential_3nn'] for c in cases)/10)*10-5),15)
 fig.suptitle('Fresh validation after paired native search\nFive seeds per engine; positive values favor the local model',fontsize=11);fig.savefig(O/'paired_gains.png',dpi=160,metadata={'Software':'V159'});fig.savefig(O/'paired_gains.svg',metadata={'Date':None});plt.close(fig)
 text=['# V159: paired native solver study','', 'This is a completed local experiment on two solver implementations. It tests transfer after feasibility-based workload selection; it is not confirmation on an untouched industrial cohort. The two engines share the N-queens benchmark and constraint-solving domain.','',f"Executed **800 native objective evaluations**, **{comp['actual_collection']['new_model_requests']} real local-model requests**, and **70 logical B20 arms** across ten saved prefixes. Each arm used ten shared prefix evaluations, seven further search evaluations and three fresh incumbent validations. No fabricated responses or inferred runtimes were used.",'','## Measured model comparisons','','Positive gain means a lower median validation runtime than the comparator. Means below weight the five seeds equally within each engine. A robust practical win requires >10% gain, different configurations, three valid solutions per arm and <=5% relative MAD. Joint wins must beat sequential 3NN, adaptive neighbor and GP-EI under all those conditions.','','| Engine | Model | Mean gain vs sequential | vs adaptive | vs GP-EI | Joint robust wins |','|---|---|---:|---:|---:|---:|']
 for e in ['cvc5','ortools']:
  for m in MODELS:
   cc=[c for c in cases if c['engine']==e and c['model']==m];gg=[100*statistics.mean(c['gains'][b] for c in cc) for b in ['sequential_3nn','adaptive_neighbor','gp_ei']];text.append(f"| {e} | {m} | {gg[0]:+.3f}% | {gg[1]:+.3f}% | {gg[2]:+.3f}% | {sum(c['joint_robust_win'] for c in cc)}/5 |")
 text+=['',f"Same-configuration model/sequential selections: {sum(c['same_configuration']['sequential_3nn'] for c in cases)}/20. Validation arms above the frozen 5% relative-MAD threshold: {sum(not a['stable'] for a in arms.values())}/70. Correct native evaluations: {comp['actual_collection']['native_correct']}/800; timeout utility penalties: {comp['actual_collection']['native_timeout_penalties']}. A penalty is a declared utility value, not a successful runtime. Unfiltered gains are retained even when they fail the practical/reliability rule.",'','## Frozen routing policies','','The exact saved historical benefit predictor and uncertainty threshold were used without fitting on these engines. Prefix features, paper-inspired signals and all decisions were hashed before any continuation. The BORA/rank rules remain checkpoint adaptations, not the complete original algorithms. Rank expectation is computed over the two real outcomes; the hindsight oracle is nondeployable.','','| Model | Policy | Calls / 10 (expected where applicable) | Equal-engine mean gain vs never |','|---|---|---:|---:|']
 for p in policies:text.append(f"| {p['model']} | {p['policy']} | {p['calls_or_expected_calls']:.2f} | {100*p['two_engine_mean_gain']:+.3f}% |")
 text+=['','## Cost and reliability','',f"Actual native collection consumed {comp['actual_collection']['native_collection_seconds']:.3f} subprocess-seconds, including {comp['actual_collection']['native_solve_seconds']:.3f} solve-seconds. End-to-end experiment time was {comp['actual_collection']['completion_seconds']:.3f} seconds. The earlier 80 feasibility probes and their failures are additional actual research cost, outside these 800 evaluations. Both branches, random controls and fresh validation were collected; none becomes free by being reused for policy analysis.",'']
 for m,v in models.items():text.append(f"- {m}: {v['ledger']['generation_requests']} starts, {v['responses']} responses; observed input/output tokens {v['usage_observed']['tokens_evaluated']}/{v['usage_observed']['tokens_predicted']}; unknown-usage requests {v['usage_unknown_requests']}; {v['invalid_or_missing']} invalid/missing responses; {v['request_wall_seconds']:.3f} request-seconds; {v['ledger']['stage_seconds']:.3f} total model-stage seconds; peak server RSS {v['ledger']['peak_server_rss_bytes']} bytes; server exit {v['ledger']['server_exit_code']}.")
 text+=['','Modeled deployment for each ten-case policy uses 200 objective evaluations plus its selected request count. `comparison.json` also gives a retrospective selected-branch collection-time proxy using measured branch and request durations; it excludes model cold-start time, which is separately logged. It is not a measured deployment run, an invoice, or an energy estimate. If a selected request has unknown duration, that proxy is unknown rather than zero. Paid/cloud inference was disabled; no new model weights were downloaded.','', '## Limits and next evidence','', 'Five repeated seeds are not five independent software systems. There are only two new implementations, a shared task/domain, different board sizes, and feasibility exposure. The historical router was trained against a different 20-search target, while this study reserves three evaluations for validation. Domain shift, this transport mismatch, local quantization, public-benchmark familiarity, one host, and validation noise limit conclusions. Some selected settings ran faster than the four feasibility probes: 16 of 70 validation medians fell below the earlier 10 ms feasibility floor (minimum 9.548 ms). The paired protocol did not include this floor in its robust-win rule; that distinction is retained rather than changing the rule after observing results. All 70 validation cells met the declared 5% MAD criterion. No learned-router generalization, equivalence, population significance, industrial performance, or journal acceptance follows from this sample. Report any positive cells alongside all unfavorable controls and seeds.','', 'The next substantive evidence should come from additional independently sourced application families with fixed workload/output contracts, selected before inspecting model gains. Do not tune a new router on these results and call them held out. Independent-host replication and an external methodological review are still missing.','', 'Evidence: `artifacts/study_v159` contains the protocol/input hashes, candidate definitions, saved prefixes/prompts and pre-continuation decisions. `results/v159_native` contains all acquisitions, seven branches per prefix, frozen incumbents, validation blocks and aggregates. `results/v159_models` contains both pinned runtimes, requests, raw responses, tokens, failures and exit receipts. Figures can be regenerated with `.venv/bin/python scripts/report_solvers_v159.py`. Collection is create-once; do not rerun the collector.']
 (ROOT/'reports/solvers_v159.md').write_text('\n'.join(text)+'\n');print(json.dumps({'joint_robust_wins':{m:sum(c['joint_robust_win'] for c in cases if c['model']==m) for m in MODELS},'native':comp['actual_collection'],'model_costs':models},indent=2))
if __name__=='__main__':main()
