"""Primary fresh-validation medians and full charged collection costs."""
import json,statistics,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];A=ROOT/'artifacts/study_v153';O=ROOT/'results/v153_native';MODELS=['smollm3_3b','qwen3_8b'];CONTROLS=['sequential_3nn','adaptive_neighbor','fixed_neighbor','random_full','random_proposal']
def read(p):return json.loads(p.read_text())
def main():
 completion=read(O/'completion.json');assert completion['acquisitions']==400
 acqs=[read(p) for p in sorted((O/'acquisitions').glob('*.json'))];assert len(acqs)==400 and all(r['status']=='correct' for r in acqs)
 val=[json.loads(s) for s in (O/'validation.jsonl').read_text().splitlines()];assert len(val)==105
 choices=read(O/'selections.json');decisions=read(A/'decisions.json')['rows'];jobs=read(A/'jobs.json');arms={}
 for x in choices:
  values=[v['value'] for v in val if (v['case'],v['arm'])==(x['case'],x['arm'])];assert len(values)==3
  search=read(O/'search'/f"{x['case']}__{x['arm']}.json");med=statistics.median(values)
  arms[(x['case'],x['arm'])]={**x,'validation_times':values,'validation_median':med,'validation_mad_fraction':statistics.median(abs(y-med) for y in values)/med,'fallback':search.get('fallback',False)}
 rows=[];models={}
 for model in MODELS:
  folder=ROOT/'results/v153_models'/model;ledger=read(folder/'ledger.json');responses=[json.loads(s) for s in (folder/'responses.jsonl').read_text().splitlines()];bykey={r['key']:r for r in responses}
  for j in jobs:
   key=j['key'];a=arms[(key,model)];dec=next(d for d in decisions if d['key']==key and d['model']==model);response=bykey.get(key);u=response['response'] if response else {}
   references={c:arms[(key,c)] for c in CONTROLS};gain={c:(r['validation_median']-a['validation_median'])/r['validation_median'] for c,r in references.items()};search_gain={c:(r['search_best']-a['search_best'])/r['search_best'] for c,r in references.items()}
   rows.append({'key':key,'seed':j['seed'],'group':'memcached_native','model':model,'arm':a,'references':references,'gains':gain,'search_gains_secondary':search_gain,'policies':dec['policies'],'fallback':a['fallback'],'same_selected_configuration_vs_sequential':a['row_id']==references['sequential_3nn']['row_id'],'same_selected_configuration_vs_adaptive':a['row_id']==references['adaptive_neighbor']['row_id'],'usage':{'generated_tokens':u.get('tokens_predicted'),'prefill_tokens':u.get('tokens_evaluated'),'request_seconds':response['wall_seconds'] if response else None}})
  rs=[r for r in rows if r['model']==model];policies={}
  for name in rs[0]['policies']:
   chosen=[r for r in rs if r['policies'][name]];mean=sum(r['gains']['sequential_3nn'] for r in chosen)/5;random=len(chosen)/5*statistics.mean(r['gains']['sequential_3nn'] for r in rs)
   policies[name]={'calls':len(chosen),'mean_gain':mean,'matched_random_expected_gain':random,'gain_above_matched_random':mean-random,'useful':sum(r['gains']['sequential_3nn']>.01 for r in chosen),'harmful':sum(r['gains']['sequential_3nn']<-.01 for r in chosen),'joint_useful':sum(r['gains']['sequential_3nn']>.01 and r['gains']['adaptive_neighbor']>.01 for r in chosen),'missed':sum(r['gains']['sequential_3nn']>.01 for r in rs)-sum(r['gains']['sequential_3nn']>.01 for r in chosen),'observed_selected_tokens_lower_bound':sum(r['usage']['generated_tokens'] or 0 for r in chosen),'observed_selected_request_seconds_lower_bound':sum(r['usage']['request_seconds'] or 0 for r in chosen),'unknown_selected_usage':sum(r['usage']['generated_tokens'] is None for r in chosen),'selected_keys':[r['key'] for r in chosen]}
  contrast={}
  for c in CONTROLS:
   ys=[r['gains'][c] for r in rs];contrast[c]={'mean_gain':statistics.mean(ys),'wins':sum(y>1e-12 for y in ys),'ties':sum(abs(y)<=1e-12 for y in ys),'losses':sum(y< -1e-12 for y in ys),'practical_wins':sum(y>.01 for y in ys),'practical_harms':sum(y<-.01 for y in ys)}
  models[model]={'ledger':ledger,'complete_responses':len(responses),'contrasts':contrast,'policies':policies,'joint_practical_wins':sum(r['gains']['sequential_3nn']>.01 and r['gains']['adaptive_neighbor']>.01 for r in rs),'hindsight_oracle_gain':statistics.mean(max(0,r['gains']['sequential_3nn']) for r in rs),'generated_tokens_lower_bound':sum(r['usage']['generated_tokens'] or 0 for r in rs),'prefill_tokens_lower_bound':sum(r['usage']['prefill_tokens'] or 0 for r in rs),'unknown_usage':sum(r['usage']['generated_tokens'] is None for r in rs)}
 summary={'scope':'prospectively frozen native paired study on feasibility-explored single family; 17search+3charged validation per arm','cases':rows,'models':models,'completion':completion,'all_correct_native_acquisitions':len(acqs),'total_search_acquisitions':sum(r['phase']!='validation' for r in acqs),'validation_acquisitions':105,'model_generation_starts':sum(x['ledger']['generation_requests'] for x in models.values()),'native_server_exit_counts':{str(v):sum(e['server_exit']==v for e in acqs) for v in sorted({e['server_exit'] for e in acqs})},'unique_native_configurations':len({r['row_id'] for r in acqs}),'native_workload_checked_operations':sum(r['measurement']['checked_operations'] for r in acqs),'validation_mad_fraction_max':max(a['validation_mad_fraction'] for a in arms.values()),'validation_arms_over_1pct_mad':sum(a['validation_mad_fraction']>.01 for a in arms.values())}
 (O/'comparison.json').write_text(json.dumps(summary,indent=2,sort_keys=True)+'\n')
 lines=['# V153: actual native paired Memcached optimization','', '**Five paired seeds, one feasibility-explored native family, two real pinned local models.** This is a prospective frozen collection, not a wholly unseen-family study or evidence of broad transfer. Every logical arm spends20objective evaluations:10sharedprefix,7newsearchconfigurations,3freshchargedrepetitions of the selected incumbent. Primary performance is median of those3fresh times. This differs from earlier20distinct-search-label studies. No validation measurement is used to select a configuration or change a controller.','',
 'Memcached1.6.45, staticlibevent2.1.13 and the V152correctness-checked native client run locally.64feature-onlysettings: threads1..8 ×requests/event[1,2,4,8,12,20,32,50]. Each fresh server completes2,048,000GET/SEToperations with byte-exact response and independent counter checks. Native timing includes the concurrent local clients; this is not isolated server throughput, native cloud deployment or a cloud-dollar optimization. Source/build/feasibility details are in native_feasibility_v152.md.','',
 f"Actual collection: **{len(acqs)}charged native acquisitions, {summary['model_generation_starts']}real model starts**, {completion['logical_B20_arms']}B20arms, {completion['seconds']:.3f}seconds/1800secondcap.295searchacquisitions plus105freshvalidationmeasurements; {summary['unique_native_configurations']}unique settings. All{len(acqs)}nativeacquisitions passed correctness. Earlier40feasibilityprobes and all historical router-training costs remain separate overhead. No free repeated labels. All server children reaped; localmodel ledgers preserve request/token/runtime caps and any failures.", '',
 '| Model / classical control | Mean validation gain | Wins/ties/losses | >1%wins / harms |','|---|---:|---|---|']
 for m,s in models.items():
  for c,x in s['contrasts'].items():lines.append(f"| {m} / {c} | {100*x['mean_gain']:+.4f}% | {x['wins']}/{x['ties']}/{x['losses']} | {x['practical_wins']}/{x['practical_harms']} |")
 lines+=['','| Model / seed | Selected setting | Validation times(s) | Gain vs sequential | Gain vs adaptive | Secondary search-best gain vs sequential |','|---|---|---|---:|---:|---:|']
 candidates=read(A/'candidates.json')
 for r in rows:
  a=r['arm'];setting=candidates['raw_features'][a['row_id']];lines.append(f"| {r['model']} / {r['seed']} | {setting} | {', '.join(f'{x:.6f}' for x in a['validation_times'])} | {100*r['gains']['sequential_3nn']:+.4f}% | {100*r['gains']['adaptive_neighbor']:+.4f}% | {100*r['search_gains_secondary']['sequential_3nn']:+.4f}% |")
 lines+=['','| Model / frozen policy | Calls /5 | Mean gain vs sequential | Above matched random | Useful / harmful | Missed useful |','|---|---:|---:|---:|---|---:|']
 for m,s in models.items():
  for name,p in s['policies'].items():lines.append(f"| {m} / {name} | {p['calls']} | {100*p['mean_gain']:+.4f}% | {100*p['gain_above_matched_random']:+.4f}% | {p['useful']}/{p['harmful']} | {p['missed']} |")
 lines+=['',f"Selected-configuration identity: {sum(r['same_selected_configuration_vs_sequential'] for r in rows)}/10model/classical pairs selected exactly the same configuration. Those observed timing differences cannot establish a configuration-selection advantage; all raw contrasts remain in the table.", '',
 'Policies were fit/calibrated only on V151existing development data grouped by ecosystem and frozen before any Memcachedprefix. Prefix-only decisions were sealed before continuation. Their training target used earlier recorded/search outcomes; the new native validation-median target is an explicit shift. Random expected gain is a retrospective matched-rate diagnostic. Hindsight oracle is nondeployable. Allfivecases form onesystemgroup; repeated seeds are not independent systems. No significance/equivalence/generalization claim follows.','']
 for m,s in models.items():
  l=s['ledger'];lines.append(f"{m}: joint >1%wins against sequential/adaptive {s['joint_practical_wins']}/5; hindsightoraclemean{100*s['hindsight_oracle_gain']:.4f}%. {l['generation_requests']}starts/{s['complete_responses']}complete responses, {s['generated_tokens_lower_bound']}observedgenerated/{s['prefill_tokens_lower_bound']}prefilltokens, {s['unknown_usage']}unknownusage; lifecycle{l['stage_seconds']:.3f}s,peakRSS{l['peak_server_rss_bytes']}bytes,serverexit{l['server_exit_code']}.")
 lines+=['',f"Validation variability: {summary['validation_arms_over_1pct_mad']}/35arms exceed1%MAD/median across3repetitions; maximum{100*summary['validation_mad_fraction_max']:.3f}%. The earlier five-repetition feasibility pass is not a guarantee for every new setting/run. Tiny differences, particularly when arms selected the same configuration, may reflect timing noise rather than optimization advantage. No repeated validation was added after seeing these values.", '',
 'Estimated deployment spends20evaluations and at mostonechosenmodelrequest/case, including its validation allocation; actual research spends400nativeevaluations plusbothmodels and earlierdevelopment. Selected-token/time estimates reuse observed historical response costs and are descriptive, with coldstart cost recorded separately. Search phases ran classical before model; validation was randomized in threecompleteblocks after all35choices were frozen. This reduces validation-order bias but cannot eliminate search-order, thermal, client/server contention or background-load effects.','',
 'Protocol clarification: frozen prompt code uses raw numeric settings and indexed level lists, whereas one protocol sentence said normalized observations. Search/projection uses normalized distances. The discrepancy was recorded before model starts; no prompt/code/decision changed mid-run. Fixed-value GET/SET checks are not full protocol conformance testing.', '',
 f"Native shutdown diagnostics: {summary['native_server_exit_counts']}. One server was killed by the configured cleanup fallback after a correct measurement and was reaped. This is retained as an operational event, not silently counted as an exit0.", '',
 'Evidence: raw native acquisition records/serverlogs, model payloads/rawresponses, candidate/prefix manifests, router coefficients/trees and decisionseals, selectionseal, complete validationplan and logs, budgets, model/backend hashes and reproduction scripts. This is one bounded native result, not Q2-readiness certification.']
 (ROOT/'reports/native_study_v153.md').write_text('\n'.join(lines)+'\n')
 import matplotlib
 matplotlib.use('Agg');matplotlib.rcParams['svg.hashsalt']='v153'
 import matplotlib.pyplot as plt
 fig,axes=plt.subplots(1,2,figsize=(11,4.5),layout='constrained')
 for ax,m in zip(axes,MODELS):
  rs=[r for r in rows if r['model']==m];x=list(range(5));ax.bar([v-.2 for v in x],[100*r['gains']['sequential_3nn'] for r in rs],.4,label='Vs sequential');ax.bar([v+.2 for v in x],[100*r['gains']['adaptive_neighbor'] for r in rs],.4,label='Vs adaptive');ax.axhline(0,color='black',lw=.7);ax.axhline(1,color='gray',ls=':',lw=.6);ax.set_xticks(x,[r['seed'] for r in rs]);ax.set_xlabel('Seed (dependent cases within one family)');ax.set_ylabel('Gain in fresh validation median (%)');ax.set_title(m);ax.grid(axis='y',alpha=.2);ax.legend(fontsize=8)
 fig.suptitle('Native Memcached: paired continuations with charged validation\n10prefix +7search +3freshvalidation =20evaluations/arm')
 fig.savefig(O/'comparison.png',dpi=150);fig.savefig(O/'comparison.svg',metadata={'Date':None});plt.close(fig)
 print(json.dumps({m:{'gain_vs_sequential':x['contrasts']['sequential_3nn']['mean_gain'],'gain_vs_adaptive':x['contrasts']['adaptive_neighbor']['mean_gain'],'joint_wins':x['joint_practical_wins'],'benefit':x['policies']['benefit']} for m,x in models.items()},indent=2))
if __name__=='__main__':main()
