"""Generate reports/model_scale_v172.md tables from results/v172_analysis/analysis.json (no hand-written numbers)."""
import argparse
from collect_smollm_v47 import ROOT, read
LABEL = {'smollm3_3b': 'SmolLM3-3B (historical draw)', 'qwen3_8b': 'Qwen3-8B (historical draw)', 'qwen3_8b_redraw': 'Qwen3-8B (V172 re-draw)', 'qwen3_14b': 'Qwen3-14B (V172)'}
DECISION = {'close_router_question': 'Qwen3-14B shows LLM-specific wins in fewer than 2 of 7 ecosystems. Per the frozen rule, the router question is closed for these local models on this hardware.',
            'scale_consistent_headroom_router_question_testable': 'Qwen3-14B reaches the 2-ecosystem threshold while the 8B re-draw does not. Per the frozen rule, this is consistent with scale-related headroom; the next step is a fresh, headroom-gated cohort.',
            'headroom_also_under_8b_resampling_scale_not_supported': 'Both Qwen3-14B and the 8B re-draw reach the threshold. Per the frozen rule, attribution to scale is not supported; the next step is a multi-draw headroom estimate.'}

def pct(x): return 'n/a' if x is None else f'{100*x:+.3f}%'

def build():
    a = read(ROOT/'results/v172_analysis/analysis.json'); s = a['summaries']; ev = a['evaluation']; rel = a['reliability']
    L = ['# V172: model-scale test of LLM-specific escalation headroom', '',
         'Generated by `scripts/report_v172.py` from `results/v172_analysis/analysis.json`. Protocol: `reports/protocol_v172.md` (frozen in `artifacts/study_v172/freeze.json`). '
         'Recorded-table cohort: 70 exposed cases in 7 ecosystems (8 engines); the new model draws were unexposed at freeze. Seeds are not independent systems; no significance test.', '',
         '## Primary estimand and frozen decision', '',
         f"LLM-specific win: beats sequential 3NN, random-full, adaptive neighbor and GP-EI each by >{100*a['margin']:.0f}%.", '',
         '| Arm | Ecosystems with a win (of 7) | Engines (of 8) | Win cases | Scored / 70 |', '|---|---:|---:|---:|---:|']
    for k in ['smollm3_3b', 'qwen3_8b', 'qwen3_8b_redraw', 'qwen3_14b']:
        x = s[k]; L.append(f"| {LABEL[k]} | {x['ecosystems_with_llm_specific_win']} | {x['engines_with_llm_specific_win']} | {x['llm_specific_win_cases']} | {x['scored']} |")
    L += ['', f"**Decision (`{a['decision']}`):** {DECISION[a['decision']]}"]
    sv = a['sensitivity_valid_responses_only']
    if a['redraw_count_is_lower_bound']:
        L += ['', f"The Qwen3-8B re-draw has {sv['qwen3_8b_redraw']['fallback_cases']} fallback cases (stage B1 stopped at the pre-declared 8 GiB server-RSS cap; stage B2 lost its server during its 30th request, cause unconfirmed but most consistent with the same cap; see `reports/protocol_v172_amendment2.md`). Fallbacks cannot be LLM-specific wins, so the re-draw's ecosystem count is a lower bound; the primary Qwen3-14B estimand is unaffected by this."]
    L += ['', '### Amendment 2 sensitivity: valid responses only (descriptive)', '', '| Arm | Valid-response cases | Fallbacks | Ecosystems covered | Ecosystems with a win | Win cases | Eq.-ecosystem gain | Headroom |', '|---|---:|---:|---:|---:|---:|---:|---:|']
    for k in ['qwen3_14b', 'qwen3_8b_redraw']:
        x = sv[k]; L.append(f"| {LABEL[k]} | {x['valid_response_cases']} | {x['fallback_cases']} | {x['ecosystems_covered']} | {x['ecosystems_with_llm_specific_win']} | {x['llm_specific_win_cases']} | {pct(x['equal_ecosystem_mean_gain_vs_sequential'])} | {pct(x['equal_ecosystem_hindsight_headroom'])} |")
    L += ['', '## Secondary measures', '',
          '| Arm | Eq.-ecosystem gain vs sequential | Log-ratio | Hindsight headroom | >1% over sequential | >1% over random-full / adaptive / GP-EI |', '|---|---:|---:|---:|---:|---:|']
    for k in ['smollm3_3b', 'qwen3_8b', 'qwen3_8b_redraw', 'qwen3_14b']:
        x = s[k]; b = x['better_than_single_switch_by_margin']
        L.append(f"| {LABEL[k]} | {pct(x['equal_ecosystem_mean_gain_vs_sequential'])} | {pct(x['equal_ecosystem_mean_log_gain_vs_sequential'])} | {pct(x['equal_ecosystem_hindsight_headroom'])} | {x['useful_over_sequential']} | {b['random_full']} / {b['adaptive_neighbor']} / {b['gp_ei']} |")
    if a['redraw_count_is_lower_bound']: L += ['', f"The Qwen3-8B re-draw row includes its {sv['qwen3_8b_redraw']['fallback_cases']} fallback cases, which rerun the historical classical fallback rule; its mean therefore mixes model and classical continuations (see the valid-only sensitivity above)."]
    L += ['', 'Win-case keys: ' + '; '.join(f"{LABEL[k]}: {', '.join(s[k]['llm_specific_win_keys']) or 'none'}" for k in ['qwen3_8b_redraw', 'qwen3_14b']), '',
          '## Paired draws (same cases)', '', '| Reference → treatment | Pairs | Treatment >1% better | >1% worse | Identical | Mean relative gain |', '|---|---:|---:|---:|---:|---:|']
    for p in a['paired']:
        L.append(f"| {LABEL[p['reference']]} → {LABEL[p['treatment']]} | {p['pairs']} | {p['treatment_better_by_margin']} | {p['treatment_worse_by_margin']} | {p['identical']} | {pct(p['mean_relative_gain'])} |")
    L += ['', '## Reliability and actual collection cost', '', '| Stage | Arm | Intended | Responses | Valid | Invalid | Attempted, no response | Unattempted | Generated / prefill tokens | Request s | Startup s | Peak RSS GB | Exit |', '|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
    for st in [k for k in rel if not k.endswith('_selection') and k != 'failed_stages']:
        r = rel[st]; L.append(f"| {st} | {r['arm']} | {r['intended']} | {r['responses']} | {r['valid']} | {r['invalid']} | {r['intended']-r['responses']-r['unattempted']} | {r['unattempted']} | {r['generated_tokens_observed']} / {r['prefill_tokens_observed']} | {r['request_seconds']:.1f} | {(r['startup_seconds'] or 0):.1f} | {r['peak_server_rss_bytes']/1e9:.2f} | {r['server_exit_code']} |")
    for s, f in rel['failed_stages'].items():
        L.append(f"\nFailed stage {s} (retained): {f['reason']}; generation requests {f['ledger']['generation_requests']}, error `{f['summary_error']}`. See `reports/protocol_v172_amendment1.md`.")
    for arm in ['qwen3_14b', 'qwen3_8b_redraw']:
        r = rel[arm+'_selection']; L.append(f"\n{LABEL[arm]} selection: {r['fallbacks']} fallbacks of {r['arms']} arms; {r['projected_proposals']} projected proposals, {r['nonzero_projection_distance']} needing nonzero projection, {r['repeated_proposals']} repeated, {r['matches_prefix']} matching an acquired prefix setting.")
    L += ['', f"Evaluation: {ev['scored_arms']}/{ev['intended_arms']} arms scored, {ev['acquisitions']} recorded acquisitions charged, {ev['seconds']:.2f} s, failures: {len(ev['failures'])}.", '',
          'Research cost also includes the 9,001,785,040-byte download, one synthetic compatibility request and five model loads (P, A1R, A2, B1, B2; A1 aborted at its pre-start port probe before launching a server). Modeled deployment would use one call plus ten recorded evaluations per escalated case. No dollar or energy estimate.', '',
          '## Scope', '', 'Exposed recorded tasks; one prompt/grammar/projection interface; one draw per case per arm; Qwen3-14B differs from 8B in more than size; neither is SNAP2\'s gpt-oss-120b. The result bears on LLM-specific headroom, not on router skill, which remains untestable without positive-bearing groups.']
    return '\n'.join(L)+'\n'

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); args = ap.parse_args(); text = build(); dest = ROOT/'reports/model_scale_v172.md'
    if args.check: assert dest.read_text() == text; print('report reproduced'); return
    assert not dest.exists(); dest.write_text(text); print('written', dest.relative_to(ROOT))

if __name__ == '__main__': main()
