"""Generate reports/snap2_model_v173.md from results/v173_analysis/analysis.json (no hand-written numbers)."""
import argparse
from collect_smollm_v47 import ROOT, read
LABEL = {'smollm3_3b': 'SmolLM3-3B (local, historical)', 'qwen3_8b': 'Qwen3-8B (local, historical)', 'qwen3_8b_redraw': 'Qwen3-8B (local, V172 re-draw, 25 fallbacks)',
         'qwen3_14b': 'Qwen3-14B (local, V172)', 'gptoss_a1': 'gpt-oss-120b arm A, draw 1 (V172 interface)', 'gptoss_a2': 'gpt-oss-120b arm A, draw 2', 'gptoss_b': 'gpt-oss-120b arm B (SNAP2-style loop)'}
DEC = {'boundary_extends_to_snap2_model_on_this_cohort': 'Neither gpt-oss-120b arm reaches LLM-specific wins in 2 of 7 ecosystems. Per the frozen rule, the no-LLM-specific-headroom boundary extends to SNAP2\'s model on this cohort.',
       'headroom_at_snap2_model_router_question_needs_fresh_cohort': 'At least one gpt-oss-120b arm reaches LLM-specific wins in 2 or more of 7 ecosystems. Per the frozen rule, LLM-specific headroom exists at SNAP2\'s model scale on this exposed cohort; a router study would need a fresh, headroom-gated cohort.'}
def pct(x): return 'n/a' if x is None else f'{100*x:+.3f}%'
def build():
    a = read(ROOT/'results/v173_analysis/analysis.json'); s = a['summaries']; r = a['reliability']
    L = ['# V173: SNAP2\'s model (gpt-oss-120b) on the recorded cohort', '', 'Generated by `scripts/report_v173.py` from `results/v173_analysis/analysis.json`. Protocol: `reports/protocol_v173.md`. 70 exposed cases, 7 ecosystems (8 engines); new hosted draws. Seeds are not independent systems; no significance test.', '',
         '## Primary estimand and frozen decision', '', 'LLM-specific win: beats sequential 3NN, random-full, adaptive neighbor and GP-EI each by >1%.', '',
         '| Arm | Ecosystems (of 7) | Engines (of 8) | Win cases | Eq.-ecosystem gain vs sequential | Log-ratio | Hindsight headroom | >1% over sequential | >1% over random / adaptive / GP-EI |', '|---|---:|---:|---:|---:|---:|---:|---:|---:|']
    for k in ['smollm3_3b', 'qwen3_8b', 'qwen3_8b_redraw', 'qwen3_14b', 'gptoss_a1', 'gptoss_a2', 'gptoss_b']:
        x = s[k]; b = x['better_than_single_switch_by_margin']
        L.append(f"| {LABEL[k]} | {x['ecosystems_with_llm_specific_win']} | {x['engines_with_llm_specific_win']} | {x['llm_specific_win_cases']} | {pct(x['equal_ecosystem_mean_gain_vs_sequential'])} | {pct(x['equal_ecosystem_mean_log_gain_vs_sequential'])} | {pct(x['equal_ecosystem_hindsight_headroom'])} | {x['useful_over_sequential']} | {b['random_full']} / {b['adaptive_neighbor']} / {b['gp_ei']} |")
    L += ['', f"**Decision (`{a['decision']}`):** {DEC[a['decision']]}", '', 'Win-case keys: ' + '; '.join(f"{LABEL[k]}: {', '.join(s[k]['llm_specific_win_keys']) or 'none'}" for k in ['gptoss_a1', 'gptoss_a2', 'gptoss_b']), '',
          '## Paired comparisons (same cases)', '', '| Reference → treatment | Pairs | Treatment >1% better | >1% worse | Identical | Mean relative gain |', '|---|---:|---:|---:|---:|---:|']
    for p in a['paired']: L.append(f"| {LABEL[p['reference']]} → {LABEL[p['treatment']]} | {p['pairs']} | {p['treatment_better_by_margin']} | {p['treatment_worse_by_margin']} | {p['identical']} | {pct(p['mean_relative_gain'])} |")
    L += ['', '## Requests, reliability and actual cost', '', '| Stage | HTTP attempts | Non-200 (of which 429) | Served by | Prompt / completion (reasoning) tokens | Reported cost USD | Request s |', '|---|---:|---:|---|---:|---:|---:|']
    for st in [k for k in r if k not in ('arm_b', 'spend_ledger') and not k.endswith('_selection')]:
        x = r[st]; L.append(f"| {st} | {x['requests']} | {x['http_errors']} ({x['rate_limited_429']}) | {', '.join(x['served_by']) or '-'} | {x['prompt_tokens']} / {x['completion_tokens']} ({x['reasoning_tokens']}) | {x['reported_cost_usd']:.5f} | {x['request_seconds']:.1f} |")
    b = r['arm_b']; sp = r['spend_ledger']
    L += ['', f"Arm A selections: draw 1 {r['gptoss_a1_selection']['fallbacks']} fallbacks / 70; draw 2 {r['gptoss_a2_selection']['fallbacks']} fallbacks / 70. Arm A evaluation: {a['evaluation_a']['scored_arms']}/{a['evaluation_a']['intended_arms']} arms, {a['evaluation_a']['acquisitions']} recorded acquisitions.",
          f"Arm B: {b['cases']} cases, {b['model_rounds']} model rounds, {b['fallback_rounds']} fallback rounds, {b['rounds_needing_retry']} rounds needing a retry, {b['collisions']} collisions, {b['cases_rebuilt_in_EB']} cases rebuilt fallback-only in EB, {b['missing_acquisitions']} missing Spark targets (charged).",
          f"Total recorded spend: ${sp['spent_usd']:.5f} over {sp['requests']} requests (reported ${sp['reported_cost_usd']:.5f}; estimated-only ${sp['estimated_only_usd']:.5f}; unknown-cost requests {sp['unknown_cost_requests']}). Client cap $3.00. The key reported a $100 limit at preflight rather than the planned $5; account credit ($5) and the client cap bounded actual exposure.",
          'Stage A1 (V172 interface at a 4,000-token cap) was stopped by the operator after truncations and HTTP 429 rate limits and is superseded by A1R under `reports/protocol_v173_amendment1.md`; P2 selected the provider by the pre-declared probe rule.',
          '', '## Scope', '', 'Hosted weights cannot be hash-verified; provider, model id, response id and usage are recorded per request. Reasoning effort medium is our choice (SNAP2 does not report its setting). Arm B adapts SNAP2\'s prompt blocks to our encodings; it is not SNAP2\'s code. Exposed recorded tasks; one draw per case per arm (two for arm A). A router remains untestable unless positives occur in several independent groups.']
    return '\n'.join(L)+'\n'
def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true'); a = ap.parse_args(); t = build(); d = ROOT/'reports/snap2_model_v173.md'
    if a.check: assert d.read_text() == t; print('report reproduced'); return
    assert not d.exists(); d.write_text(t); print('written', d.relative_to(ROOT))
if __name__ == '__main__': main()
