"""Sampling-seed reliability, nested descriptive means and cost completeness."""
import csv,itertools,json,os,statistics
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
os.environ.setdefault('MPLCONFIGDIR',str(ROOT/'.cache/sampling_v114'))
import matplotlib
matplotlib.use('Agg');matplotlib.rcParams['svg.hashsalt']='sampling-v114'
import matplotlib.pyplot as plt
from collect_smollm_v47 import read,write
PRIMARY=['batch_3nn','full_sequential_3nn']

def summarize(s):
 cases=s['cases'];assert len(cases)==36 and len({r['key'] for r in cases})==36
 prefixes=[]
 for key in sorted({r['base_key'] for r in cases}):
  rows=sorted([r for r in cases if r['base_key']==key],key=lambda r:r['sampling_seed']);assert len(rows)==3 and {r['sampling_seed'] for r in rows}=={1009,2027,3041}
  valid=[r for r in rows if not r['fallback']];sets=[set(r['selected_rows']) for r in valid];pairs=list(itertools.combinations(sets,2));jac=[len(a&b)/len(a|b) for a,b in pairs]
  joint=[all(r['gains'][a]>=.05 for a in PRIMARY) and not r['fallback'] for r in rows]
  labels={a:['benefit' if r['gains'][a]>=.05 else 'harm' if r['gains'][a]<=-.05 else 'between' for r in valid] for a in PRIMARY}
  prefixes.append(dict(base_key=key,family=rows[0]['family'],optimization_seed=rows[0]['optimization_seed'],valid_replicas=len(valid),fallbacks=3-len(valid),joint_useful_valid_replicas=sum(joint),valid_only_benefit_classification_changes={a:len(set(v))>1 for a,v in labels.items()},valid_only_joint_classification_changes=len({all(r['gains'][a]>=.05 for a in PRIMARY) for r in valid})>1,valid_pair_count=len(pairs),mean_jaccard=statistics.mean(jac) if jac else None,all_valid_sets_equal=(all(a==sets[0] for a in sets) if len(sets)>=2 else None),distinct_valid_sets=len({tuple(sorted(a)) for a in sets}),distinct_valid_targets=len({r['target'] for r in valid}),policy_mean_gains={a:statistics.mean(r['gains'][a] for r in rows) for a in PRIMARY},policy_gain_min={a:min(r['gains'][a] for r in rows) for a in PRIMARY},policy_gain_max={a:max(r['gains'][a] for r in rows) for a in PRIMARY},valid_gain_range={a:max(r['gains'][a] for r in valid)-min(r['gains'][a] for r in valid) if valid else None for a in PRIMARY},sampling_seeds=[r['sampling_seed'] for r in rows]))
 groups={f:{a:statistics.mean(p['policy_mean_gains'][a] for p in prefixes if p['family']==f) for a in PRIMARY} for f in sorted({p['family'] for p in prefixes})}
 thresholds=[dict(margin=t,valid_joint_ge=sum(not r['fallback'] and all(r['gains'][a]>=t for a in PRIMARY) for r in cases),valid_joint_strict_gt=sum(not r['fallback'] and all(r['gains'][a]>t for a in PRIMARY) for r in cases),full_policy_joint_ge=sum(all(r['gains'][a]>=t for a in PRIMARY) for r in cases)) for t in [0,.02,.05,.1]]
 valid=[r for r in cases if not r['fallback']]
 return dict(scope='exploratory fixed-prefix replication; repeats nested within12prefixes and6exposed groups',intended=36,valid=len(valid),fallbacks=36-len(valid),unattempted=sum(r['status']=='unattempted' for r in cases),prefixes=prefixes,groups=groups,group_first_policy_mean={a:statistics.mean(g[a] for g in groups.values()) for a in PRIMARY},valid_only_group_first_mean={a:statistics.mean(statistics.mean(r['gains'][a] for r in valid if r['family']==f) for f in groups if any(r['family']==f for r in valid)) if valid else None for a in PRIMARY},valid_only_groups_represented=len({r['family'] for r in valid}),threshold_grid=thresholds,prefixes_with_valid_joint_change=sum(p['valid_only_joint_classification_changes'] for p in prefixes),prefixes_with_multiple_valid_sets=sum(p['distinct_valid_sets']>1 for p in prefixes),prefixes_with_multiple_valid_targets=sum(p['distinct_valid_targets']>1 for p in prefixes),collection=dict(new_requests=s['requests'],responses=s['responses'],new_recorded_acquisitions=s['actual_new_recorded_acquisitions'],model_stage_seconds=s['ledger']['stage_seconds'],peak_rss_bytes=s['ledger']['peak_server_rss_bytes'],allocated_output_tokens=s['ledger']['allocated_output_tokens'],returned_generated_tokens=sum(r['generated_tokens'] or 0 for r in cases),missing_request_usage=sum(r['missing_request_usage'] for r in cases),reported_actual_prefill_tokens=s['reported_actual_prefill_tokens'],summed_full_context_tokens=s['summed_full_context_tokens'],retries=s['ledger']['retries'],external_spend_usd=0))

def main():
 s=read(ROOT/'results/v114_analysis/summary.json');d=summarize(s);out=ROOT/'results/v114_analysis';write(out/'sampling_reliability.json',d)
 with (out/'replica_contrasts.csv').open('w') as f:
  writer=csv.writer(f);writer.writerow(['case','group','optimization_seed','sampling_seed','status','fallback','target',*PRIMARY])
  for r in s['cases']:writer.writerow([r['key'],r['family'],r['optimization_seed'],r['sampling_seed'],r['status'],r['fallback'],r['target'],*[r['gains'][a] for a in PRIMARY]])
 fig,axs=plt.subplots(1,2,figsize=(12,6),sharey=True,layout='constrained')
 for ax,control in zip(axs,PRIMARY):
  for y,p in enumerate(d['prefixes']):
   rs=sorted([r for r in s['cases'] if r['base_key']==p['base_key']],key=lambda r:r['sampling_seed'])
   vals=[100*r['gains'][control] for r in rs];ax.plot([min(vals),max(vals)],[y,y],color='#777777',lw=1)
   for offset,r in zip([-.14,0,.14],rs):ax.scatter(100*r['gains'][control],y+offset,marker='x' if r['fallback'] else 'o',color='#D55E00' if r['fallback'] else '#0072B2',s=24)
  ax.axvline(0,color='gray',lw=1);ax.axvline(5,color='green',ls='--',lw=1);ax.axvline(-5,color='red',ls='--',lw=1)
  ax.set(title='vs '+('batch3NN' if control=='batch_3nn' else 'sequential3NN'),xlabel='Relative gain (%); positive favors LLM',yticks=range(12),yticklabels=[p['family']+' / '+str(p['optimization_seed']) for p in d['prefixes']]);ax.invert_yaxis() if not ax.yaxis_inverted() else None
 fig.suptitle('V114: three new sampling seeds per fixed prefix\nLines are observed ranges, not confidence intervals; x denotes fallback')
 fig.savefig(out/'sampling.png',dpi=170,metadata={'Software':'matplotlib'});fig.savefig(out/'sampling.svg',metadata={'Date':None});plt.close(fig)
 a=d['collection'];threshold=next(x for x in d['threshold_grid'] if x['margin']==.05)
 text=['# V114: fixed-prefix sampling reliability','',f"Executed **{a['new_requests']} real local model requests** for36intended replicas of12saved prefixes from six exposed software groups. Returned {a['responses']}responses; {d['valid']}valid final selections, {d['fallbacks']}fallback-policy conditions, {d['unattempted']}unattempted conditions. Scoring acquired **{a['new_recorded_acquisitions']}recorded outcomes**, independently charging ten per replica after its original ten-label prefix. These are real model responses and recorded-table acquisitions, not new native runtime measurements.",'',f"**{threshold['valid_joint_ge']}/36** intended replicas produced a valid>=5%gain over BOTH strong classical controls. Full fallback-policy mean gain, averaging within prefix and then equally across groups: **{d['group_first_policy_mean']['batch_3nn']:+.2%}** versus batch3NN and **{d['group_first_policy_mean']['full_sequential_3nn']:+.2%}** versus sequential3NN.",'','|Software group|Mean gain vs batch3NN|Mean gain vs sequential3NN|','|---|---:|---:|']
 for family,g in d['groups'].items():text.append(f"|{family}|{g['batch_3nn']:+.2%}|{g['full_sequential_3nn']:+.2%}|")
 text+=['','## What varies at the same checkpoint','',f"{d['prefixes_with_multiple_valid_sets']}/12prefixes produced more than one valid selected configuration set; {d['prefixes_with_multiple_valid_targets']}/12produced more than one final incumbent value. Joint>=5%benefit classification changed across valid replicas for {d['prefixes_with_valid_joint_change']}/12prefixes. Exact-set agreement, pairwise Jaccard, all min/max gains and valid/fallback denominators are saved for every prefix. Each group still contributes only one group to the evidence, regardless of response count.",'','|Prefix|Valid replicas|Distinct selected sets|Distinct final values|Mean Jaccard|Valid joint>=5%wins|','|---|---:|---:|---:|---:|---:|']
 for p in d['prefixes']:
  jac='unknown' if p['mean_jaccard'] is None else f"{p['mean_jaccard']:.3f}"
  text.append(f"|{p['base_key']}|{p['valid_replicas']}/3|{p['distinct_valid_sets']}|{p['distinct_valid_targets']}|{jac}|{p['joint_useful_valid_replicas']}/3|")
 text+=['','## Actual collection cost and scope','',f"Model lifecycle {a['model_stage_seconds']:.3f}s; peak sampled RSS {a['peak_rss_bytes']:,}bytes. Allocated output tokens {a['allocated_output_tokens']}; returned generated tokens {a['returned_generated_tokens']}; actual reported prefill tokens {a['reported_actual_prefill_tokens']}; summed full contexts {a['summed_full_context_tokens']}. Missing request usage:{a['missing_request_usage']}; retries:{a['retries']}. No new downloads or external spending. Prefix/control acquisition and historical inference costs remain in their old ledgers; they are not newly measured or free.",'', 'One deployed continuation would select one answer and spend ten new outcomes after its ten-outcome prefix. Running three candidates here costs three requests and thirty continuation acquisitions per prefix; selecting the best response after scoring all three would exceed that deployment budget. No best-seed deployment result is claimed. Model startup is reported separately in the raw ledger; electricity/hardware cost remains unknown.','', 'All messages, candidate order, model/runtime, parser, prompt scaffold and nonthinking parameters were fixed. Only the model sampling seed changes within a prefix. Runtime nondeterminism may still contribute, and three samples cannot estimate a calibrated benefit probability. No new router was fit, no prompt was selected by outcomes, and historicalV103responses are not pooled into the primary sample.','', 'This is an exploratory robustness result on six already exposed groups, two optimization seeds per group, one local model bundle and one host. It does not create36independent tasks, establish a population guarantee, resolve public-data contamination, or demonstrate useful benefit-aware routing. Native timing qualifications fromV113remain separate. A journal tier is not measured by the experiment.','', '![All36intended replica outcomes](../results/v114_analysis/sampling.png)']
 (ROOT/'reports/sampling_v114.md').write_text('\n'.join(text)+'\n');print(json.dumps({k:d[k] for k in ['valid','fallbacks','unattempted','group_first_policy_mean','prefixes_with_multiple_valid_sets','prefixes_with_multiple_valid_targets','prefixes_with_valid_joint_change','collection']}))
if __name__=='__main__':main()
