"""V177 offline reproduction of the reviewer audit bundle. Run from the unpacked bundle:

    python scripts/reproduce_bundle_v177.py            # everything that can run on this host
    python scripts/reproduce_bundle_v177.py --core     # skip host-dependent checks

Every command runs with PYTHONPATH=src:scripts/guard_v176, so any network connection or host lookup raises (no API
calls are possible). Nothing is downloaded, no model is run and no objective is measured. Scripts that regenerate
reports or figures overwrite them in place; after the run, every file listed in BUNDLE_MANIFEST_V177.json is re-hashed
and must be byte-identical. Differences in .png/.svg figures are reported separately because rendering can depend on
installed fonts; any other change is a failure. Exit status 0 means every core command passed and no data file changed.
"""
import argparse, hashlib, json, os, subprocess, sys, tempfile, time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TESTS = ['test_audit_v171.py', 'test_v172.py', 'test_v173.py', 'test_revision_v175.py', 'test_audit_bundle_v176.py', 'test_audit_bundle_v177.py', 'test_router_v151.py', 'test_router_v147.py',
         'test_controllers_v154.py', 'test_gp_continuations_v155.py', 'test_native_study_v153.py', 'test_headroom_v165.py', 'test_headroom_analysis_v165.py',
         'test_ezr_v170.py', 'test_spark_v145.py', 'test_hadoop_v148.py', 'test_models_v141.py']
LOCATION_DEPENDENT_TEST = 'tests/synthetic/test_v172.py::test_server_command_is_historical_command'
S = lambda n, *a: ['scripts/'+n+'.py', *a]
CORE = [  # (name, argv, what it establishes)
    ('audit_v171', S('audit_v171', '--check'), 'V171 audit of the recorded (3B/8B) and native cohorts recomputed byte-for-byte'),
    ('analyze_v172', S('analyze_v172', '--check'), 'Qwen3-14B / Qwen3-8B re-draw analysis recomputed byte-for-byte'),
    ('report_v172', S('report_v172', '--check'), 'V172 report tables regenerated byte-for-byte'),
    ('verify_v172', S('verify_v172_relocated_v176'), 'independent V172 replay: prompts, projections, charged acquisitions, targets, mutation rejection'),
    ('analyze_v173', S('analyze_v173', '--check'), 'gpt-oss-120b analysis recomputed byte-for-byte'),
    ('report_v173', S('report_v173', '--check'), 'V173 report tables regenerated byte-for-byte'),
    ('verify_v173', S('verify_v173'), 'independent V173 replay: 539 hosted requests, cost ledger, acquisitions, leakage and mutation checks'),
    ('revision_v174', S('revision_v174', '--check'), 'first-revision analysis (weightings, deployable policy, routers rerun, operations) byte-for-byte'),
    ('revision_v175', S('revision_v175', '--check'), 'second-revision analysis (reweighting, matching, accounting) byte-for-byte'),
    ('check_tables_v176', S('check_tables_v176'), 'every result-table row and key in-text number of main.tex matches the outputs'),
    ('verify_router_v132', S('verify_router_v132'), 'independent replay of the frozen V132 controllers and their zero-call decisions on WavPack and FFTW'),
    ('verify_feedback_v136', S('verify_feedback_v136', '--compact'), 'independent replay of the masked-feedback experiment (V136): responses, acquisitions, arms'),
    ('verify_models_v141', S('verify_models_v141', '--compact'), 'independent V141 replay of 60 local-model requests and 600 acquisitions (compact: no model-weight hashing)'),
    ('verify_spark_v145', S('verify_spark_v145'), 'independent Spark replay (2,000 charged acquisitions)'),
    ('verify_hadoop_v148', S('verify_hadoop_v148'), 'independent Hadoop replay (1,200 charged outcomes)'),
    ('verify_router_v151', S('verify_router_v151'), 'independent controller algebra, fold membership, thresholds and aggregates'),
    ('report_router_v151', S('report_router_v151'), 'V151 controller report and figures regenerated'),
    ('verify_controllers_v154', S('verify_controllers_v154'), 'independent BORA-inspired / rank-reliability checkpoint replay'),
    ('report_controllers_v154', S('report_controllers_v154'), 'V154 report and figures regenerated'),
    ('verify_gp_v155', S('verify_gp_v155'), 'independent GP-EI posterior, EI maximum and charged-source replay'),
    ('report_gp_v155', S('report_gp_v155'), 'V155 GP-EI comparison regenerated'),
    ('report_native_v153', S('report_native_v153'), 'V153 native (Memcached) comparison regenerated'),
    ('verify_solvers_v159', S('verify_solvers_v159'), 'native cvc5 / OR-Tools collection replay from raw logs'),
    ('verify_apps_v163', S('verify_apps_v163'), 'native application collection replay from raw logs'),
    ('verify_apps_v164', S('verify_apps_v164'), 'native application collection replay from saved data'),
    ('report_headroom_v165', S('report_headroom_v165'), 'exhaustive-search headroom analysis regenerated from saved measurements'),
    ('posthoc_headroom_v165', S('posthoc_headroom_v165'), 'post-hoc headroom sensitivity regenerated'),
    ('verify_headroom_v165', S('verify_headroom_v165'), 'independent exhaustive-search acquisition, selection and fresh-validation replay (ripgrep/hnswlib)'),
    ('report_ezr_v170', S('report_ezr_v170'), 'native re-validation comparison (Table 6 source) regenerated from saved measurements'),
    ('synthesis_ezr_v170', S('synthesis_ezr_v170'), 'native synthesis (Table 6 values) regenerated'),
    ('pytest', ['-m', 'pytest', '-q', '-p', 'no:cacheprovider', *[f'tests/synthetic/{t}' for t in TESTS], '--deselect', LOCATION_DEPENDENT_TEST], 'unit and consistency tests'),
]
HOST = [  # (name, argv, required interpreter, what it establishes)
    ('pytest_ezr_bridge', ['-m', 'pytest', '-q', '-p', 'no:cacheprovider', 'tests/synthetic/test_ezr_v169.py'], '/opt/homebrew/bin/python3.13', 'EZR bridge tests; need Python 3.13 at this path'),
]
RECEIPT = 'not rerun by this offline workflow; original-workspace execution receipt included'
NOT_IN_BUNDLE = {  # these never report PASS here: a receipt records a past run, it does not re-verify anything
    'verify_native_study_v153': {'status': RECEIPT, 'receipt': 'artifacts/study_v153/replay.json', 'why': 'hashes the compiled memcached and libevent binaries, which are not included'},
    'verify_apps_v168': {'status': RECEIPT, 'receipt': 'artifacts/study_v168/replay.json', 'why': 'imports the pinned Polars 1.35.2 native runtime (125 MB), which is not included'},
    'verify_ezr_v169': {'status': RECEIPT, 'receipt': 'artifacts/study_v169/replay.json', 'why': 'imports the pinned Polars runtime and runs EZR under the recorded Python 3.13 interpreter'},
    'verify_ezr_v170': {'status': RECEIPT, 'receipt': 'artifacts/study_v170/replay.json', 'why': 'raw re-validation imports the pinned Polars and XGBoost runtimes and reads the Covertype and flights data, which are not included'},
    'seal_research_v176 --verify-only': {'status': 'not rerun by this offline workflow', 'why': 'needs every historically sealed file, including model weights and native runtimes; scripts/verify_bundle_v177.py checks what is included, and a listed hash of an omitted file does not verify its contents'},
    LOCATION_DEPENDENT_TEST: {'status': 'deselected', 'why': 'compares an absolute path; the same comparison runs relocated inside verify_v172'},
}

def digest(p):
    h = hashlib.sha256()
    with open(p, 'rb') as f:
        for b in iter(lambda: f.read(1 << 20), b''): h.update(b)
    return h.hexdigest()

def run(name, argv, env, log):
    t = time.time(); p = subprocess.run([sys.executable, *argv], cwd=ROOT, env=env, capture_output=True, text=True, timeout=1800)
    log.write(f'\n===== {name}: {" ".join(argv)}\n{p.stdout[-6000:]}\n{p.stderr[-6000:]}\n'); log.flush()
    return {'name': name, 'argv': argv, 'returncode': p.returncode, 'seconds': round(time.time()-t, 1), 'last_line': (p.stdout.strip().splitlines() or [''])[-1][:300]}

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--core', action='store_true', help='skip host-dependent checks'); ap.add_argument('--out', type=Path, default=ROOT/'REPRODUCTION_RESULT_V177.json'); a = ap.parse_args()
    manifest = json.loads((ROOT/'BUNDLE_MANIFEST_V177.json').read_text())['files']
    corrupt = [n for n, m in manifest.items() if not (ROOT/n).exists() or digest(ROOT/n) != m['sha256']]
    if corrupt: sys.exit(f'bundle does not match BUNDLE_MANIFEST_V177.json before running: {corrupt[:10]}')
    tmp = tempfile.mkdtemp(prefix='bundle-v177-'); env = dict(os.environ, PYTHONPATH=os.pathsep.join(['src', 'scripts/guard_v176']), MPLCONFIGDIR=tmp, PYTHONDONTWRITEBYTECODE='1', PYTHONHASHSEED='0')
    results = []
    with open(Path(tmp)/'reproduction.log', 'w') as log:
        for name, argv, why in CORE:
            r = run(name, argv, env, log); r.update(kind='core', establishes=why); results.append(r); print(f"{'PASS' if r['returncode'] == 0 else 'FAIL'}  {name:26s} {r['seconds']:6.1f}s  {r['last_line'][:110]}", flush=True)
        for name, argv, interp, why in HOST:
            if a.core or not Path(interp).exists():
                results.append({'name': name, 'kind': 'host_dependent', 'status': 'skipped', 'reason': f'{interp} not present' if not a.core else '--core', 'establishes': why}); print(f'SKIP  {name}'); continue
            r = run(name, argv, env, log); r.update(kind='host_dependent', establishes=why); results.append(r); print(f"{'PASS' if r['returncode'] == 0 else 'FAIL'}  {name:26s} {r['seconds']:6.1f}s  {r['last_line'][:110]}", flush=True)
        r = run('verify_bundle_v177', S('verify_bundle_v177'), env, log); r.update(kind='core', establishes='bundle hashes, evidence-manifest chain and coverage of earlier seals'); results.append(r)
        print(f"{'PASS' if r['returncode'] == 0 else 'FAIL'}  verify_bundle_v177          {r['last_line'][:110]}")
    changed = [n for n, m in manifest.items() if digest(ROOT/n) != m['sha256']]
    figures = [n for n in changed if n.endswith(('.png', '.svg'))]; data = [n for n in changed if n not in figures]
    failed = [r['name'] for r in results if r.get('returncode', 0) != 0]
    out = {'passed': not failed and not data, 'failed_commands': failed, 'changed_data_files': data, 'changed_figure_files': figures,
           'files_checked_after_run': len(manifest), 'python': sys.version.split()[0], 'commands': results, 'not_reproducible_from_bundle': NOT_IN_BUNDLE, 'log': str(Path(tmp)/'reproduction.log')}
    a.out.write_text(json.dumps(out, indent=1)+'\n')
    print(json.dumps({k: out[k] for k in ['passed', 'failed_commands', 'changed_data_files', 'changed_figure_files', 'files_checked_after_run', 'log']}, indent=1))
    sys.exit(0 if out['passed'] else 1)

if __name__ == '__main__': main()
