"""Descriptive synthesis of both retained adapters; no objective acquisitions."""
import json,statistics
from table_check_v119 import ROOT,read,write,MODES
OUT=ROOT/'results/v120_synthesis'
def main():
    summaries={v:read(ROOT/f'results/v{v}_analysis/summary.json') for v in [119,120]}
    comparisons={v:read(ROOT/f'results/v{v}_analysis/comparison.json') for v in [119,120]}
    assert all(s['complete'] for s in summaries.values())
    a,b=summaries[119],summaries[120];pc=read(ROOT/'results/v119_classical/policy_precommit.json')
    assert [r['optimization_seed'] for r in a['cases']]==[r['optimization_seed'] for r in b['cases']]
    for old,new in zip(a['cases'],b['cases']):assert old['references']==new['references']
    total={'real_model_requests':sum(s['new_model_requests'] for s in summaries.values()),'recorded_objective_acquisitions':sum(s['actual_classical_acquisitions']+s['actual_new_llm_acquisitions'] for s in summaries.values()),'generated_tokens':sum(s['actual_generated_tokens'] for s in summaries.values()),'reported_prefill_tokens':sum(s['actual_prefill_tokens'] for s in summaries.values()),'allocated_output_tokens':sum(s['ledger']['allocated_output_tokens'] for s in summaries.values()),'model_lifecycle_seconds_sum':sum(s['ledger']['stage_seconds'] for s in summaries.values()),'external_spend_usd':0,'new_download_bytes':0}
    joint=[all(r['gains'][m]>=.05 for m in MODES[:2]) and not r['fallback'] for r in b['cases']]
    transfer={name:{'escalations':sum(mask),'joint_practical_opportunities_missed':sum(g and not m for g,m in zip(joint,mask))} for name,mask in pc['masks'].items()}
    result={'scope':'Descriptive one-family external recorded-label check and exploratory adapter follow-up; not independent native validation, no causal grammar attribution or learned-router generalization','groups':1,'prefixes':5,'collection':total,'transferred_masks':transfer,'v119_valid_continuations':5-comparisons[119]['fallbacks'],'v120_valid_continuations':5-comparisons[120]['fallbacks'],'v120_joint_5pct_wins':sum(joint),'v120_comparisons':comparisons[120]['comparisons'],'cumulative_real_model_requests':3974+total['real_model_requests'],'cumulative_recorded_acquisitions':28458+total['recorded_objective_acquisitions']}
    write(OUT/'summary.json',result)
    text=['# V119–V120: a real opportunity, but the transferred router missed it','',
      'The constrained Qwen3-8B adapter selected configurations with lower mean published latency than all four fixed classical controls on the WordCount table. Two of five prefixes improved by at least5% against both co-primary controls. The frozen benefit-aware controller escalated in zero cases and therefore missed both joint opportunities. This is evidence of an opportunity in this recorded table, not a successful benefit-aware controller or a journal-readiness guarantee.','',
      '## Scope and sequence','',
      'V119 chose the original owner WordCount table by its feature/workload semantics and froze its source, protocol, implementation and all controller masks before continuation outcomes. Available exposure auditing found no previous Storm objective results. It deliberately restored the limited published-label scope already used by the older recorded-data studies; it did not loosen V52\'s stronger correctness/measurement admission gates. Original latency semantics, per-run success and executed-version provenance remain unverified.','',
      'All five V119 real responses produced five-character configuration strings instead of candidate IDs and failed the frozen parser. Each case used its predeclared classical fallback. V119 quality differences therefore compare that fallback with other controls: they do not measure successful LLM choices. The original generated V119 figure uses the generic term "LLM arm"; read it specifically as an all-fallback policy. No failed answer was reinterpreted, silently repaired or discarded.','',
      'After seeing these failures, V120 froze one follow-up using the existing V91 grammar-constrained greedy adapter. It reused every saved prefix, shortlist, message, classical reference and router decision. All50 real one-token requests returned valid IDs, yielding five complete continuations without retries. V120 is exploratory on an exposed table. Grammar, decoding settings and template handling differ together, so the validity/quality change cannot be attributed to grammar alone. It is not a measured automatic repair policy.','',
      '## Actual quality result','',
      '| Control | Mean relative gain, V120 | Wins / ties / losses | Valid ≥5% wins |','|---|---:|---:|---:|']
    for m,c in comparisons[120]['comparisons'].items():text.append(f"| {m} | {100*c['seed_mean']:.3f}% | {c['wins']}/{c['ties']}/{c['losses']} | {c['valid_5pct_wins']}/5 |")
    text+=['',
      'The practical-margin criterion fixed before V120 collection was met: positive mean against both co-primary controls and at least one joint5% win. Seed71 was worse than batch/sequential/portfolio, seed23 tied all controls, and seed53 improved against batch but lost against sequential. All remain in the analysis. No interval/p-value is calculated from five correlated seeds as though they were five independent systems.','',
      'The old V6 benefit and uncertainty policies both escalated zero times. Their training model and normalized-loss target differ from this Qwen/relative-gain task; they are unchanged transfer diagnostics, not newly fitted estimators. Their zero cost is accompanied by missed improvements. Matched-rate random at zero also never escalates, giving no useful discrimination test. Hindsight headroom is descriptive and non-deployable.','',
      '## Actual research cost versus deployment estimates','',
      f"Both adapters together: **{total['real_model_requests']} real requests**, **{total['recorded_objective_acquisitions']} charged recorded acquisitions**, {total['generated_tokens']} generated tokens/{total['allocated_output_tokens']} allocated, {total['reported_prefill_tokens']} reported prefill tokens and {total['model_lifecycle_seconds_sum']:.3f}s summed server lifecycle time. Five initial format failures plus five valid constrained continuations. No retries, missing response usage, cloud calls, new downloads or external spend. All servers stopped. The request count includes every failed-format answer.",'',
      'The350 acquisitions are50 shared prefixes +200 classical branches +50 initial fallback branches +50 constrained branches. Every logical optimization arm remains B20. Replaying already acquired cells for integrity checks does not acquire labels for a selection algorithm. These are recorded-table accesses, not350 fresh Storm executions.','',
      f"V119 lifecycle {a['ledger']['stage_seconds']:.3f}s, peak RSS {a['ledger']['peak_server_rss_bytes']:,}bytes; V120 lifecycle {b['ledger']['stage_seconds']:.3f}s, peak RSS {b['ledger']['peak_server_rss_bytes']:,}bytes. V120's mean sum of request wall time per continuation was {statistics.mean(r['model_seconds'] for r in b['cases']):.3f}s; excludes startup, controller/oracle overhead and native application costs. Request-level prefill is smaller under cache reuse; token counts are not evidence of equal work per request across adapters.",'',
      'Estimated deployment uses one prefix and one selected branch. V119 allocates one model request/escalation; V120 allocates ten. We collected both plus all controls for research; these costs are not erased. No inference-dollar tariff or native wall-time break-even is claimed.','',
      '## What this changes and what remains','',
      'Earlier exposed-family practical-margin failures do not justify a universal claim of no LLM opportunity: this WordCount table now supplies a counterexample under a different existing adapter. It does not retroactively validate the original free-output interface or justify selecting favorable systems. Keep the older six-family results, the new external format failure and the exploratory positive continuation separate.','',
      'The most important next experiment is to freeze this exact constrained adapter and a group-disjoint development/evaluation plan on additional software families, selected by source/feature eligibility before opening targets. Keep all Storm variants out of any purported new test group. Fit a controller for this exact model/interface/relative-gain target only on development groups, with a never-escalate default where cost-adjusted evidence is weak. Do not refit on these five seeds and call the result held-out. A causal adapter ablation and native measurement replication are separate subsequent questions.','',
      '## Evidence and replay','',
      '`results/v119_reasoning/` and `results/v120_qwen/` retain real raw outputs, starts, templates and runtime provenance. `results/v119_classical/` retains all prefixes, controls and precommitted masks; each analysis directory retains50 continuation acquisition events. `reports/protocol_v119.freeze.json` and `protocol_v120.freeze.json` precede their respective collections. `scripts/verify_table_model_v119.py` and `verify_table_model_v120.py` independently replay source cells, requests, selections and B20 costs. Regenerate this summary and the paired figure with `scripts/synthesize_table_v120.py`. Synthetic fixtures are confined to tests.']
    (ROOT/'reports/paired_adapters_v120.md').write_text('\n'.join(text)+'\n')
    import matplotlib
    matplotlib.use('Agg');matplotlib.rcParams['svg.hashsalt']='paired-adapters-v120'
    import matplotlib.pyplot as plt
    fig,axes=plt.subplots(1,2,figsize=(11,4.2),sharey=True)
    for ax,v,title in zip(axes,[119,120],['V119: all five answers invalid\nPlanned classical fallback used','V120: five valid constrained continuations\nExploratory follow-up']):
        for m in MODES[:2]:ax.plot(range(5),[100*r['gains'][m] for r in summaries[v]['cases']],marker='o',label=m.replace('_',' '))
        ax.axhline(0,color='gray',lw=.8);ax.axhline(5,color='gray',ls=':',label='5% margin');ax.set_xticks(range(5),[11,23,37,53,71]);ax.set_title(title,fontsize=10);ax.set_xlabel('Optimization seed (same one Storm family)');ax.grid(alpha=.15)
    axes[0].set_ylabel('Relative gain in recorded latency (%)');axes[1].legend(fontsize=8);fig.tight_layout();fig.savefig(OUT/'paired.png',dpi=160);fig.savefig(OUT/'paired.svg',metadata={'Date':None});plt.close(fig)
    print(json.dumps(result,indent=2))
if __name__=='__main__':main()
