"""Separate application results from two compatible control extensions; no fitting."""
import statistics
from collect_smollm_v47 import ROOT,read,write
def main():
    cases=[];collections=[];arms=[]
    for stage in [169,170]:
        d=read(ROOT/f'results/v{stage}_ezr/comparison.json');cases.extend({**c,'stage':stage} for c in d['cases']);arms.extend(d['arms']);collections.append(d['collection'])
    assert len(cases)==60 and len(arms)==270
    rows=[]
    for engine in ['cvc5','ortools','ripgrep','hnswlib','polars','xgboost']:
        for model in ['smollm3_3b','qwen3_8b']:
            cs=[c for c in cases if c['engine']==engine and c['model']==model];assert len(cs)==5
            rows.append({'engine':engine,'model':model,'cases':5,'mean_gains':{name:statistics.mean(c['gains'][name] for c in cs) for name in cs[0]['gains']},'robust_wins':{name:sum(c['robust_practical_wins'][name] for c in cs) for name in cs[0]['gains']},'joint_robust_wins':sum(c['joint_robust_win'] for c in cs)})
    total={'new_native_outcomes':sum(c['acquisitions'] for c in collections),'new_native_workload_executions':sum(c['query_training_executions'] for c in collections),'new_search_labels':420,'new_validation_outcomes':810,'new_source_arms':60,'historical_fixed_selections':210,'source_optimizer_cpu_seconds':sum(c['source_optimizer_process_cpu_seconds'] for c in collections),'collection_wall_seconds':sum(c['seconds'] for c in collections),'quality_penalties':sum(c['quality_penalties'] for c in collections),'new_model_requests':0,'new_downloads':0}
    write(ROOT/'artifacts/study_v170/synthesis.json',{'scope':'descriptive per-implementation results; no pooled significance or new independent systems','per_application_model':rows,'collection':total,'validation_quality_invalid_cells':sum(not a['quality_valid'] for a in arms),'validation_unstable_cells':sum(not a['stable'] for a in arms),'validation_below_floor_cells':sum(not a['above_floor'] for a in arms)})
    text=['# Source-executed EZR baseline extension: six implementations','','The unchanged pinned EZR acquisition code now executes as two explicitly adapted checkpoint controls across all six recent native implementations. Existing real-model choices are revalidated beside these controls. This addresses source-code execution and comparator coverage; it does not test an improved model or retrain the controller.','','| Implementation | Model | Gain vs sequential | vs EZR centroid | vs EZR Bayes | Joint robust wins /5 |','|---|---|---:|---:|---:|---:|']
    for r in rows:text.append(f"| {r['engine']} | {r['model']} | {100*r['mean_gains']['sequential_3nn']:+.3f}% | {100*r['mean_gains']['ezr_upstream_centroid']:+.3f}% | {100*r['mean_gains']['ezr_upstream_bayes']:+.3f}% | {r['joint_robust_wins']} |")
    text+=['','All comparator gains, individual cases, same-setting flags and noise/quality diagnostics are retained in the two stage comparison.json files. Gains use same-stage fresh-validation medians; old primary results remain unchanged. No new model request, response, prompt or source download occurred.','',f"New collection: {total['new_native_outcomes']} outcomes; {total['new_native_workload_executions']} workload executions; {total['new_search_labels']} search labels and {total['new_validation_outcomes']} validation labels; {total['collection_wall_seconds']:.3f} seconds across two bounded stages. Sixty new source-method B20 arms reuse300historically acquired prefix outcomes (600logical cached prefix callbacks). Revalidation of210historical selected settings costs630additional outcomes outside their closed policy budgets.",'','The six implementation labels are not six randomly sampled independent production tasks. cvc5/OR-Tools share constructed N-queens workloads; Polars shares an earlier DuckDB flight workload; ripgrep/hnswlib use compact real public inputs. Repeated seeds, source-method variants and revalidation do not add software systems. Historical searches and new source searches occurred at different times. These secondary results provide no population significance, useful-controller guarantee or journal-quartile certification.','','Reports: reports/ezr_v169.md and reports/ezr_v170.md. Protocol/source adaptations: reports/protocol_v169.md and reports/protocol_v170.md. All independent-host, broader-model and full original-method limitations remain.']
    (ROOT/'reports/ezr_synthesis_v170.md').write_text('\n'.join(text)+'\n')
    print(total)
if __name__=='__main__':main()
